/**
 * Full Flutter curriculum for AlefYa — 15 stages / 50+ lessons.
 */
import { stage } from "./expand.mjs";

function L(
  slug,
  order,
  duration,
  titleAr,
  titleEn,
  summaryAr,
  summaryEn,
  focusAr,
  focusEn,
  ideas,
  code,
  stack = "dart",
) {
  return {
    slug,
    order,
    duration,
    title: { ar: titleAr, en: titleEn },
    summary: { ar: summaryAr, en: summaryEn },
    focus: { ar: focusAr, en: focusEn },
    stack,
    ideas: ideas.map(([ta, ba, te, be]) => ({
      title: { ar: ta, en: te },
      body: { ar: ba, en: be },
    })),
    codeSource: code,
    faqs: [
      {
        q: {
          ar: `ما أهم نقطة في «${titleAr}»؟`,
          en: `What's the key point of “${titleEn}”?`,
        },
        a: {
          ar: "افهم النموذج الذهني أولاً ثم طبّق المثال. هذا أساس مسار ألف ياء.",
          en: "Lock the mental model first, then practice the example. That's the AlefYa approach.",
        },
      },
      {
        q: { ar: "هل أحتاج أدوات خارج الموقع؟", en: "Do I need tools outside the site?" },
        a: {
          ar: "المفاهيم والتمارين هنا كافية للفهم؛ نفّذ محلياً عندما يطلب الدرس ذلك.",
          en: "Concepts and exercises here are enough to learn; run locally when the lesson asks.",
        },
      },
      {
        q: { ar: "كيف أتأكد أنني جاهز؟", en: "How do I know I'm ready?" },
        a: {
          ar: "أنهِ قائمة التحقق واشرح الفكرة لزميل بدون نسخ أعمى.",
          en: "Finish the checklist and explain the idea without blind copying.",
        },
      },
      {
        q: { ar: "ماذا بعد هذا الدرس؟", en: "What's next?" },
        a: {
          ar: "اتبع ترتيب المرحلة فقط — كل درس يبني على السابق.",
          en: "Follow the stage order only — each lesson builds on the previous.",
        },
      },
    ],
    nextHint: {
      ar: "انتقل للدرس التالي في نفس المرحلة بالترتيب.",
      en: "Continue to the next lesson in this stage, in order.",
    },
  };
}

function buildTrack({ slug, order, title, tagline, description, color, hours, stages }) {
  const track = {
    slug,
    order,
    title,
    tagline,
    description,
    color,
    estimatedHours: hours,
    stages: stages.map((s) => s.slug),
  };
  const stageMap = {};
  for (const s of stages) {
    stageMap[s.slug] = stage(s.slug, s.order, s.title, s.description, s.lessons);
  }
  return [track, stageMap];
}

const [flutterTrack, flutterStages] = buildTrack({
  slug: "flutter",
  order: 6,
  title: { ar: "Flutter", en: "Flutter" },
  tagline: {
    ar: "من Dart حتى تطبيق جوال جاهز للإطلاق",
    en: "From Dart to a shippable cross-platform app",
  },
  description: {
    ar: "مسار Flutter الكامل: Dart، Widgets، التخطيط، التنقل، الحالة، الشبكة، التخزين، الرسوم، الاختبار، ثم مشروع تسليم.",
    en: "A complete Flutter path: Dart, widgets, layout, navigation, state, networking, storage, animation, testing, then a shippable project.",
  },
  color: "#02569B",
  hours: 180,
  stages: [
    {
      slug: "01-dart-foundations",
      order: 1,
      title: { ar: "أساسيات Dart", en: "Dart foundations" },
      description: { ar: "لغة Flutter من الصفر", en: "Flutter's language from zero" },
      lessons: [
        L("01-why-flutter", 1, 40, "لماذا Flutter؟", "Why Flutter?", "أين يُستخدم ولماذا يُطلب.", "Where it's used and why demand is high.",
          "Flutter يوحّد iOS وAndroid بقاعدة كود واحدة.", "Flutter unifies iOS and Android with one codebase.",
          [["منصة واحدة", "تطبيق واحد لمنصتين عبر محرك الرسم.", "One codebase", "One app for two platforms via the rendering engine."],
           ["سوق العمل", "مطلوب في الشركات والوكالات لسرعة التسليم.", "Job market", "In demand where teams need fast delivery."]],
          "void main() {\n  print('Hello Flutter');\n}"),
        L("02-dart-syntax", 2, 45, "صيغة Dart", "Dart syntax", "متغيرات، دوال، null safety.", "Vars, functions, null safety.",
          "Dart أساس كل Widget — أتقنها قبل الواجهة.", "Dart underpins every widget — master it before UI.",
          [["Null safety", "الأنواع غير القابلة للـ null تقلّل أعطال الإنتاج.", "Null safety", "Non-nullable types cut production crashes."],
           ["الدوال", "named parameters وarrow functions شائعة.", "Functions", "Named parameters and arrow functions are common."]],
          "String greet(String? name) => 'Hi ${name ?? 'guest'}';"),
        L("03-control-flow", 3, 40, "التدفق الشرطي والحلقات", "Control flow & loops", "if، switch، for، while.", "if, switch, for, while.",
          "منطق التطبيق يبدأ من شروط وحلقات واضحة.", "App logic starts with clear conditions and loops.",
          [["switch", "مفيد مع enums والحالات المحدودة.", "switch", "Great with enums and finite states."],
           ["collections loops", "for-in وmap/where على القوائم.", "Collection loops", "for-in plus map/where on lists."]],
          "for (final item in ['a', 'b']) {\n  print(item);\n}"),
        L("04-collections", 4, 45, "المجموعات", "Collections", "List، Map، Set.", "List, Map, Set.",
          "القوائم والخرائط أساس الشاشات والحالة.", "Lists and maps underpin screens and state.",
          [["List", "ترتيب وعناصر متكررة ممكنة.", "List", "Ordered; duplicates allowed."],
           ["Map", "مفاتيح وقيم — مثالي لـ JSON.", "Map", "Keys and values — ideal for JSON."]],
          "final scores = <String, int>{'quiz': 90};\nfinal tags = <String>{'dart', 'flutter'};"),
      ],
    },
    {
      slug: "02-dart-oop-async",
      order: 2,
      title: { ar: "OOP وAsync في Dart", en: "Dart OOP & async" },
      description: { ar: "فئات ومستقبلات", en: "Classes and futures" },
      lessons: [
        L("01-classes", 1, 45, "الفئات والكائنات", "Classes & objects", "class، fields، methods.", "class, fields, methods.",
          "نماذج Flutter تُبنى من classes.", "Flutter models are built from classes.",
          [["الحقول", "final يقلّل الأخطاء.", "Fields", "final reduces bugs."],
           ["methods", "سلوك مرتبط بالبيانات.", "Methods", "Behavior tied to data."]],
          "class User {\n  final String id;\n  User(this.id);\n}"),
        L("02-constructors", 2, 40, "المُنشئات", "Constructors", "named وfactory.", "Named and factory.",
          "المنشئات المسماة لغة يومية في Flutter.", "Named constructors are daily Flutter vocabulary.",
          [["named", "User.guest() أوضح من أعلام.", "Named", "User.guest() beats boolean flags."],
           ["factory", "يتحكم بإرجاع النسخة.", "Factory", "Controls which instance is returned."]],
          "class Point {\n  final double x, y;\n  const Point(this.x, this.y);\n  factory Point.origin() => const Point(0, 0);\n}"),
        L("03-futures", 3, 45, "Future وasync/await", "Futures & async/await", "العمليات غير المتزامنة.", "Asynchronous work.",
          "كل شبكة وملف في Flutter يمر عبر Future.", "Every network and file call goes through Future.",
          [["async", "دالة تُرجع Future تلقائياً.", "async", "Function returns a Future."],
           ["await", "ينتظر النتيجة دون تجميد الواجهة إن أُحسن الاستخدام.", "await", "Waits without freezing UI when used well."]],
          "Future<String> load() async {\n  await Future.delayed(const Duration(milliseconds: 200));\n  return 'ok';\n}"),
        L("04-streams", 4, 45, "Streams", "Streams", "تدفق أحداث متكرر.", "Ongoing event sequences.",
          "Streams مفيدة للاستماع المستمر (مثل مواضع).", "Streams power continuous listening (e.g. positions).",
          [["listen", "اشترك ثم ألغِ الاشتراك.", "listen", "Subscribe, then cancel."],
           ["async*", "توليد قيم متعددة عبر الزمن.", "async*", "Yield multiple values over time."]],
          "Stream<int> ticks() async* {\n  for (var i = 0; i < 3; i++) {\n    yield i;\n    await Future.delayed(const Duration(milliseconds: 100));\n  }\n}"),
      ],
    },
    {
      slug: "03-flutter-setup",
      order: 3,
      title: { ar: "إعداد Flutter", en: "Flutter setup" },
      description: { ar: "الأدوات وأول مشروع", en: "Tooling and first project" },
      lessons: [
        L("01-sdk-tools", 1, 40, "SDK والأدوات", "SDK & tooling", "Flutter SDK وdoctor.", "Flutter SDK and doctor.",
          "بيئة صحيحة تمنع نصف أخطاء المبتدئين.", "A healthy toolchain prevents half of beginner bugs.",
          [["flutter doctor", "يشخّص النواقص.", "flutter doctor", "Diagnoses missing pieces."],
           ["قنوات", "stable للتعلم اليومي.", "Channels", "stable for daily learning."]],
          "flutter doctor\nflutter --version", "bash"),
        L("02-first-project", 2, 45, "أول مشروع", "First project", "create وتشغيل.", "create and run.",
          "أنشئ مشروعاً وافهم هيكل المجلدات.", "Create a project and learn the folder layout.",
          [["lib/", "كود التطبيق هنا.", "lib/", "App code lives here."],
           ["pubspec.yaml", "الاعتماديات والأصول.", "pubspec.yaml", "Dependencies and assets."]],
          "flutter create alefya_starter\ncd alefya_starter\nflutter run", "bash"),
        L("03-hot-reload", 3, 35, "Hot reload وHot restart", "Hot reload & restart", "دورة تطوير سريعة.", "Fast iteration loop.",
          "Hot reload يسرّع التعلم والتجريب.", "Hot reload speeds learning and experimentation.",
          [["reload", "يحفظ الحالة غالباً.", "reload", "Often preserves state."],
           ["restart", "يعيد التشغيل من الصفر.", "restart", "Restarts from scratch."]],
          "// Edit Text → save → see UI update with hot reload"),
      ],
    },
    {
      slug: "04-widgets-basics",
      order: 4,
      title: { ar: "أساسيات Widgets", en: "Widget basics" },
      description: { ar: "كل شيء Widget", en: "Everything is a widget" },
      lessons: [
        L("01-widget-tree", 1, 45, "شجرة الـ Widgets", "The widget tree", "تكوين الواجهة كشجرة.", "UI as a tree.",
          "فهم الشجرة يمنع أخطاء setState العشوائية.", "Understanding the tree prevents random setState bugs.",
          [["التركيب", "الصغير يبني الكبير.", "Composition", "Small widgets build large UIs."],
           ["BuildContext", "موقعك في الشجرة.", "BuildContext", "Your place in the tree."]],
          "class Hello extends StatelessWidget {\n  const Hello({super.key});\n  @override\n  Widget build(BuildContext context) => const Text('AlefYa');\n}"),
        L("02-stateless", 2, 40, "StatelessWidget", "StatelessWidget", "واجهة بلا حالة محلية.", "UI without local state.",
          "ابدأ بـ Stateless كلما أمكن.", "Prefer Stateless whenever possible.",
          [["props عبر الحقول", "البيانات تدخل من الخارج.", "Fields as props", "Data comes from outside."],
           ["const", "يُحسّن الأداء عند الإمكان.", "const", "Improves performance when possible."]],
          "class TitleText extends StatelessWidget {\n  const TitleText(this.text, {super.key});\n  final String text;\n  @override\n  Widget build(BuildContext context) => Text(text);\n}"),
        L("03-stateful", 3, 45, "StatefulWidget", "StatefulWidget", "حالة محلية تتغير.", "Local changing state.",
          "التفاعل يحتاج State منفصلة عن الـ Widget.", "Interaction needs State separate from the Widget.",
          [["createState", "يربط الـ Widget بحالته.", "createState", "Binds widget to its state."],
           ["setState", "يطلب إعادة البناء.", "setState", "Requests a rebuild."]],
          "class Counter extends StatefulWidget {\n  const Counter({super.key});\n  @override\n  State<Counter> createState() => _CounterState();\n}"),
        L("04-keys", 4, 40, "Keys", "Keys", "متى ولماذا تستخدم Key.", "When and why to use Key.",
          "Keys تحفظ هوية العناصر عند إعادة الترتيب.", "Keys preserve identity when children reorder.",
          [["ValueKey", "مفتاح بالقيمة.", "ValueKey", "Key by value."],
           ["أخطاء شائعة", "نسيان المفتاح في القوائم الديناميكية.", "Common mistake", "Forgetting keys in dynamic lists."]],
          "ListTile(key: ValueKey(item.id), title: Text(item.title))"),
      ],
    },
    {
      slug: "05-layout-responsive",
      order: 5,
      title: { ar: "التخطيط والاستجابة", en: "Layout & responsive UI" },
      description: { ar: "Row، Column، والمرونة", en: "Row, Column, and flexibility" },
      lessons: [
        L("01-row-column", 1, 45, "Row وColumn", "Row & Column", "المحاور الأساسية.", "Main layout axes.",
          "Flex layout هو يوميات مطوّر Flutter.", "Flex layout is daily Flutter work.",
          [["mainAxis", "اتجاه التوزيع.", "mainAxis", "Distribution direction."],
           ["crossAxis", "المحاذاة العرضية.", "crossAxis", "Cross-axis alignment."]],
          "Column(children: const [Text('A'), Text('B')])"),
        L("02-expanded-flexible", 2, 40, "Expanded وFlexible", "Expanded & Flexible", "ملء المساحة بذكاء.", "Fill space wisely.",
          "Expanded يمنع overflow شائع.", "Expanded prevents common overflow.",
          [["Expanded", "يأخذ الباقي.", "Expanded", "Takes the remainder."],
           ["Flexible", "مرونة مع حدود.", "Flexible", "Flex with constraints."]],
          "Row(children: [Expanded(child: Text('fills'))])"),
        L("03-constraints", 3, 45, "القيود والحجم", "Constraints & sizing", "كيف تُحسب الأحجام.", "How sizes are decided.",
          "Flutter: القيود تنزل والأحجام تصعد.", "Constraints go down; sizes go up.",
          [["BoxConstraints", "حدود الوالد للابن.", "BoxConstraints", "Parent limits for child."],
           ["overflow", "علامة أن القيود كُسرت.", "Overflow", "A sign constraints were broken."]],
          "SizedBox(width: 120, height: 40, child: Text('fixed'))"),
        L("04-media-query", 4, 40, "MediaQuery والاستجابة", "MediaQuery & responsiveness", "تكيّف مع الشاشة.", "Adapt to the screen.",
          "الشاشات تختلف — صمّم بمرونة.", "Screens differ — design flexibly.",
          [["size", "عرض وارتفاع الشاشة.", "size", "Screen width and height."],
           ["padding", "احترام الـ notches.", "padding", "Respect notches/safe areas."]],
          "final w = MediaQuery.sizeOf(context).width;"),
      ],
    },
    {
      slug: "06-material-theming",
      order: 6,
      title: { ar: "Material والثيم", en: "Material & theming" },
      description: { ar: "مظهر موحّد للتطبيق", en: "Consistent app look" },
      lessons: [
        L("01-scaffold", 1, 40, "Scaffold", "Scaffold", "هيكل الشاشة الأساسي.", "Basic screen scaffold.",
          "Scaffold يجمع AppBar والجسم والـ FAB.", "Scaffold holds AppBar, body, and FAB.",
          [["appBar", "شريط علوي.", "appBar", "Top bar."],
           ["body", "المحتوى الرئيسي.", "body", "Main content."]],
          "Scaffold(appBar: AppBar(title: const Text('AlefYa')), body: const Center(child: Text('Hi')))"),
        L("02-theme-data", 2, 45, "ThemeData", "ThemeData", "ألوان وخطوط مركزية.", "Central colors and typography.",
          "الثيم يمنع تكرار الأنماط يدوياً.", "Theming stops hand-duplicating styles.",
          [["colorScheme", "مصدر الألوان.", "colorScheme", "Color source of truth."],
           ["textTheme", "سلم الطباعة.", "textTheme", "Type scale."]],
          "ThemeData(colorScheme: ColorScheme.fromSeed(seedColor: Colors.teal), useMaterial3: true)"),
        L("03-common-widgets", 3, 40, "ودجات Material الشائعة", "Common Material widgets", "Button، Card، ListTile.", "Button, Card, ListTile.",
          "مكتبة جاهزة تسرّع الواجهات.", "A ready library speeds up UIs.",
          [["ListTile", "صف قائمة قياسي.", "ListTile", "Standard list row."],
           ["Card", "سطح مرتفع للمحتوى.", "Card", "Elevated content surface."]],
          "Card(child: ListTile(title: Text('Lesson'), onTap: () {}))"),
      ],
    },
    {
      slug: "07-navigation",
      order: 7,
      title: { ar: "التنقل والمسارات", en: "Navigation & routes" },
      description: { ar: "بين الشاشات بأمان", en: "Move between screens safely" },
      lessons: [
        L("01-navigator-stack", 1, 45, "مكدس Navigator", "Navigator stack", "push وpop.", "push and pop.",
          "التنقل مكدس شاشات.", "Navigation is a screen stack.",
          [["push", "أضف شاشة.", "push", "Add a screen."],
           ["pop", "ارجع للخلف.", "pop", "Go back."]],
          "Navigator.push(context, MaterialPageRoute(builder: (_) => const NextPage()));"),
        L("02-named-routes", 2, 40, "المسارات المسماة", "Named routes", "تنظيم أوضح.", "Cleaner structure.",
          "الأسماء تساعد التطبيقات الأكبر.", "Names help larger apps.",
          [["routes map", "جدول المسارات.", "routes map", "Route table."],
           ["onGenerateRoute", "مرونة إضافية.", "onGenerateRoute", "Extra flexibility."]],
          "Navigator.pushNamed(context, '/lesson');"),
        L("03-pass-args", 3, 40, "تمرير المعاملات", "Passing arguments", "بيانات بين الشاشات.", "Data between screens.",
          "مرّر معرّفات لا كائنات ضخمة إن أمكن.", "Pass ids rather than huge objects when possible.",
          [["constructor args", "بسيط للشاشات القريبة.", "Constructor args", "Simple for nearby screens."],
           ["RouteSettings", "مع named routes.", "RouteSettings", "With named routes."]],
          "Navigator.push(context, MaterialPageRoute(builder: (_) => DetailPage(id: lessonId)));"),
        L("04-go-router-intro", 4, 45, "مقدمة go_router", "Intro to go_router", "توجيه حديث.", "Modern routing.",
          "go_router شائع للـ deep links والمسارات المعقّدة.", "go_router is popular for deep links and complex routes.",
          [["declarative", "المسار يعكس الحالة.", "Declarative", "Route reflects state."],
           ["deep links", "روابط تفتح شاشة مباشرة.", "Deep links", "Links open a screen directly."]],
          "// GoRouter(routes: [GoRoute(path: '/', builder: (_, __) => Home())])"),
      ],
    },
    {
      slug: "08-forms-input",
      order: 8,
      title: { ar: "النماذج والإدخال", en: "Forms & input" },
      description: { ar: "تحقق وإرسال", en: "Validate and submit" },
      lessons: [
        L("01-text-fields", 1, 40, "حقول النص", "Text fields", "TextEditingController.", "TextEditingController.",
          "الإدخال أساس كل نموذج تسجيل أو بحث.", "Input powers every signup or search form.",
          [["controller", "اقرأ/اكتب النص.", "controller", "Read/write text."],
           ["dispose", "حرّر الموارد.", "dispose", "Free resources."]],
          "final c = TextEditingController();\n// dispose c in State.dispose"),
        L("02-form-validate", 2, 45, "Form والتحقق", "Form & validation", "GlobalKey<FormState>.", "GlobalKey<FormState>.",
          "التحقق يمنع بيانات فاسدة.", "Validation blocks bad data.",
          [["validator", "أرجع رسالة أو null.", "validator", "Return message or null."],
           ["save", "اجمع القيم بعد النجاح.", "save", "Collect values after success."]],
          "Form(key: formKey, child: TextFormField(validator: (v) => (v == null || v.isEmpty) ? 'Required' : null))"),
        L("03-focus-keyboard", 3, 35, "التركيز ولوحة المفاتيح", "Focus & keyboard", "FocusNode وScroll.", "FocusNode and scroll.",
          "تجربة إدخال جيدة تقلّل إحباط المستخدم.", "Good input UX reduces user frustration.",
          [["FocusNode", "تحكّم بالتركيز.", "FocusNode", "Control focus."],
           ["keyboard insets", "لا تخفِ الحقل تحت اللوحة.", "Keyboard insets", "Don't hide fields under the keyboard."]],
          "FocusScope.of(context).unfocus();"),
      ],
    },
    {
      slug: "09-local-state",
      order: 9,
      title: { ar: "الحالة المحلية", en: "Local state" },
      description: { ar: "setState بوعي", en: "setState with intent" },
      lessons: [
        L("01-setstate-discipline", 1, 40, "انضباط setState", "setState discipline", "ماذا تضع داخله.", "What belongs inside.",
          "setState رخيص فقط إن كان النطاق صغيراً.", "setState is cheap only at small scope.",
          [["نطاق ضيق", "لا تعِد بناء الشجرة كلها.", "Narrow scope", "Don't rebuild the whole tree."],
           ["اشتقاقات", "احسب بدلاً من تخزين الزائد.", "Derived values", "Compute instead of over-storing."]],
          "setState(() => count++);"),
        L("02-lifting-state", 2, 45, "رفع الحالة", "Lifting state", "مشاركة بين أبناء.", "Share among children.",
          "ارفع الحالة لأقرب والد مشترك.", "Lift state to the nearest shared parent.",
          [["مصدر واحد", "تجنب نسختين من الحقيقة.", "Single source", "Avoid two sources of truth."],
           ["callbacks", "الأبناء يبلّغون الوالد.", "Callbacks", "Children notify the parent."]],
          "// Parent holds selectedId; children receive it + onSelect"),
        L("03-inherited-widget", 3, 45, "InheritedWidget", "InheritedWidget", "تمرير للأسفل بكفاءة.", "Efficient downward pass.",
          "أساس Provider وأنماط أخرى.", "Foundation for Provider and similar patterns.",
          [["dependOn", "الاشتراك في التغيير.", "dependOn", "Subscribe to changes."],
           ["updateShouldNotify", "متى يعاد البناء.", "updateShouldNotify", "When to rebuild."]],
          "// Theme.of(context) uses InheritedWidget under the hood"),
      ],
    },
    {
      slug: "10-app-state",
      order: 10,
      title: { ar: "حالة التطبيق", en: "App-wide state" },
      description: { ar: "Provider وRiverpod وBloc", en: "Provider, Riverpod, and Bloc" },
      lessons: [
        L("01-why-app-state", 1, 40, "متى تتجاوز الحالة المحلية", "When local state is not enough", "حدود setState.", "Limits of setState.",
          "التطبيقات الحقيقية تحتاج حالة مشتركة.", "Real apps need shared state.",
          [["شاشات متعددة", "نفس البيانات في أكثر من مكان.", "Many screens", "Same data in many places."],
           ["آثار جانبية", "تحميل وحفظ مركزيان.", "Side effects", "Central load/save."]],
          "// prefer a state package for shared app state"),
        L("02-provider", 2, 45, "Provider", "Provider", "ChangeNotifier بسيط.", "Simple ChangeNotifier.",
          "Provider مدخل شائع وواضح.", "Provider is a common clear entry point.",
          [["ChangeNotifier", "أعلِم المستمعين.", "ChangeNotifier", "Notify listeners."],
           ["Consumer", "أعد بناء جزء فقط.", "Consumer", "Rebuild only a slice."]],
          "class Counter extends ChangeNotifier {\n  int value = 0;\n  void inc() { value++; notifyListeners(); }\n}"),
        L("03-riverpod", 3, 45, "Riverpod", "Riverpod", "مزوديّات بلا BuildContext إجباري.", "Providers without mandatory BuildContext.",
          "Riverpod يقلّل أخطاء السياق ويُسهّل الاختبار.", "Riverpod reduces context bugs and eases testing.",
          [["ProviderScope", "جذر التطبيق.", "ProviderScope", "App root."],
           ["ref.watch", "إعادة البناء عند التغيير.", "ref.watch", "Rebuild on change."]],
          "final countProvider = StateProvider<int>((ref) => 0);"),
        L("04-bloc-idea", 4, 40, "فكرة Bloc/Cubit", "Bloc/Cubit idea", "أحداث وحالات.", "Events and states.",
          "Bloc يفصل واجهة المستخدم عن منطق الأعمال.", "Bloc separates UI from business logic.",
          [["events", "ماذا طلب المستخدم.", "Events", "What the user asked."],
           ["states", "ماذا تعرض الواجهة.", "States", "What the UI shows."]],
          "// emit(Loading()) → emit(Ready(items))"),
      ],
    },
    {
      slug: "11-networking",
      order: 11,
      title: { ar: "الشبكة وJSON", en: "Networking & JSON" },
      description: { ar: "APIs موثوقة", en: "Reliable APIs" },
      lessons: [
        L("01-http-get", 1, 45, "طلبات HTTP", "HTTP requests", "GET أساسي.", "Basic GET.",
          "معظم التطبيقات تتكلم مع خادم.", "Most apps talk to a server.",
          [["http/dio", "مكتبات الشبكة.", "http/dio", "Network libraries."],
           ["status codes", "افحص النجاح صراحة.", "Status codes", "Check success explicitly."]],
          "final res = await http.get(Uri.parse('https://api.example.com/tracks'));\nif (res.statusCode != 200) throw Exception('fail');"),
        L("02-json-models", 2, 45, "نماذج fromJson", "fromJson models", "تحويل آمن.", "Safe mapping.",
          "لا تتعامل مع Map عارية في كل الشاشات.", "Don't pass raw Maps around every screen.",
          [["fromJson", "ابنِ الكائن من الخريطة.", "fromJson", "Build object from map."],
           ["null checks", "الحقول الاختيارية.", "Null checks", "Optional fields."]],
          "factory Track.fromJson(Map<String, dynamic> j) => Track(slug: j['slug'] as String);"),
        L("03-error-loading", 3, 40, "تحميل وأخطاء", "Loading & errors", "حالات الواجهة الثلاث.", "The three UI states.",
          "loading / data / error نمط لا غنى عنه.", "loading / data / error is non-negotiable.",
          [["skeleton", "عرض انتظار واضح.", "Skeleton", "Clear waiting UI."],
           ["retry", "أعد المحاولة بوعي.", "Retry", "Retry intentionally."]],
          "// if (loading) spinner; else if (error) retry; else list"),
        L("04-auth-headers", 4, 40, "ترويسات ومصادقة", "Headers & auth", "Bearer tokens.", "Bearer tokens.",
          "لا تضع الأسرار في الكود المصدر.", "Never hardcode secrets in source.",
          [["Authorization", "مرّر الرمز بأمان.", "Authorization", "Pass the token safely."],
           ["401", "حدّث الجلسة أو أعد الدخول.", "401", "Refresh session or re-login."]],
          "headers: {'Authorization': 'Bearer $token'}"),
      ],
    },
    {
      slug: "12-persistence",
      order: 12,
      title: { ar: "التخزين المحلي", en: "Local persistence" },
      description: { ar: "حفظ بين الجلسات", en: "Survive app restarts" },
      lessons: [
        L("01-shared-prefs", 1, 40, "SharedPreferences", "SharedPreferences", "إعدادات بسيطة.", "Simple settings.",
          "مناسب للأعلام والتفضيلات لا للبيانات الكبيرة.", "Fine for flags/prefs — not big datasets.",
          [["get/set", "قيم بدائية.", "get/set", "Primitive values."],
           ["async", "كل القراءة/الكتابة غير متزامنة.", "async", "All reads/writes are async."]],
          "final p = await SharedPreferences.getInstance();\nawait p.setBool('dark', true);"),
        L("02-files", 2, 40, "الملفات", "Files", "مسارات التطبيق.", "App directories.",
          "احفظ الملفات في المسارات المسموحة فقط.", "Write only in allowed app directories.",
          [["path_provider", "اعثر على المجلدات.", "path_provider", "Locate directories."],
           ["encoding", "UTF-8 للنصوص.", "Encoding", "UTF-8 for text."]],
          "final dir = await getApplicationDocumentsDirectory();"),
        L("03-local-db", 3, 45, "قاعدة محلية خفيفة", "Light local DB", "sqflite / drift فكرة.", "sqflite / drift idea.",
          "عندما تكبر البيانات تحتاج جداول.", "When data grows you need tables.",
          [["schema", "صمّم الجداول أولاً.", "Schema", "Design tables first."],
           ["migrations", "خطّط للترقية.", "Migrations", "Plan upgrades."]],
          "// CREATE TABLE progress(lesson_slug TEXT PRIMARY KEY, done INTEGER)"),
      ],
    },
    {
      slug: "13-animation-gesture",
      order: 13,
      title: { ar: "الرسوم والإيماءات", en: "Animation & gestures" },
      description: { ar: "حركة هادفة", en: "Meaningful motion" },
      lessons: [
        L("01-implicit-anim", 1, 40, "رسوم ضمنية", "Implicit animations", "AnimatedContainer.", "AnimatedContainer.",
          "ابدأ بالضمني قبل Controllers.", "Start implicit before controllers.",
          [["duration", "زمن الانتقال.", "duration", "Transition time."],
           ["curve", "إيقاع الحركة.", "curve", "Motion easing."]],
          "AnimatedContainer(duration: const Duration(milliseconds: 250), width: open ? 200 : 80)"),
        L("02-animation-controller", 2, 45, "AnimationController", "AnimationController", "تحكم صريح.", "Explicit control.",
          "للمشاهد المعقّدة تحتاج Controllers.", "Complex scenes need controllers.",
          [["Ticker", "يربط بالإطارات.", "Ticker", "Ties to frames."],
           ["dispose", "أوقف المتحكم.", "dispose", "Dispose the controller."]],
          "// controller = AnimationController(vsync: this, duration: Duration(milliseconds: 300))"),
        L("03-gestures", 3, 40, "الإيماءات", "Gestures", "Tap، Drag، Dismissible.", "Tap, drag, dismissible.",
          "الإيماءات تجعل الواجهة ملموسة.", "Gestures make UI tactile.",
          [["GestureDetector", "التقاط الإيماءة.", "GestureDetector", "Capture the gesture."],
           ["Dismissible", "سحب للحذف شائع.", "Dismissible", "Swipe-to-delete is common."]],
          "GestureDetector(onTap: () {}, child: const Text('Tap me'))"),
      ],
    },
    {
      slug: "14-testing-devtools",
      order: 14,
      title: { ar: "الاختبار والأدوات", en: "Testing & DevTools" },
      description: { ar: "ثقة قبل الإطلاق", en: "Confidence before ship" },
      lessons: [
        L("01-unit-tests", 1, 40, "اختبارات الوحدة", "Unit tests", "منطق بلا واجهة.", "Logic without UI.",
          "اختبر النماذج والدوال أولاً.", "Test models and functions first.",
          [["test()", "حالة واحدة.", "test()", "One case."],
           ["expect", "تأكيد النتيجة.", "expect", "Assert the result."]],
          "test('greet', () {\n  expect(greet(null), 'Hi guest');\n});"),
        L("02-widget-tests", 2, 45, "اختبارات الودجات", "Widget tests", "ضخ واجهة خفيفة.", "Pump a light UI.",
          "Widget tests تمسك انحدارات الواجهة مبكراً.", "Widget tests catch UI regressions early.",
          [["pumpWidget", "ابنِ الشجرة.", "pumpWidget", "Build the tree."],
           ["find", "اعثر على النص/المفتاح.", "find", "Find text/key."]],
          "await tester.pumpWidget(const MaterialApp(home: Hello()));\nexpect(find.text('AlefYa'), findsOneWidget);"),
        L("03-devtools", 3, 35, "Flutter DevTools", "Flutter DevTools", "أداء وإعادة بناء.", "Performance and rebuilds.",
          "راقب ما يُعاد بناؤه ولماذا.", "Watch what rebuilds and why.",
          [["Inspector", "الشجرة بصرياً.", "Inspector", "Visual tree."],
           ["Performance", "إطارات بطيئة.", "Performance", "Slow frames."]],
          "flutter pub global activate devtools\nflutter pub global run devtools", "bash"),
      ],
    },
    {
      slug: "15-capstone-ship",
      order: 15,
      title: { ar: "مشروع وتسليم", en: "Capstone & shipping" },
      description: { ar: "من الفكرة إلى المتجر", en: "From idea to store" },
      lessons: [
        L("01-architecture", 1, 45, "هيكلة المشروع", "Project architecture", "طبقات واضحة.", "Clear layers.",
          "افصل UI عن البيانات عن الحالة.", "Separate UI, data, and state.",
          [["features/", "مجلد لكل ميزة.", "features/", "One folder per feature."],
           ["repositories", "مصدر البيانات.", "Repositories", "Data access."]],
          "// lib/features/tracks/data|domain|presentation"),
        L("02-capstone-screens", 2, 55, "شاشات المشروع", "Capstone screens", "قائمة + تفاصيل + تقدم.", "List + detail + progress.",
          "اجمع Widgets والحالة والشبكة في تطبيق صغير.", "Combine widgets, state, and networking in a small app.",
          [["قائمة", "مسارات/دروس.", "List", "Tracks/lessons."],
           ["تفاصيل", "محتوى + حالة إنجاز.", "Detail", "Content + completion state."]],
          "// Build a lessons list screen for AlefYa-style content"),
        L("03-build-release", 3, 45, "بناء الإصدار", "Release builds", "APK/IPA وفحوصات.", "APK/IPA and checks.",
          "الإصدار يختلف عن وضع التطوير.", "Release differs from debug.",
          [["flutter build", "أنتج حزمة الإصدار.", "flutter build", "Produce a release artifact."],
           ["signing", "وقّع Android/iOS بشكل صحيح.", "Signing", "Sign Android/iOS correctly."]],
          "flutter build apk --release", "bash"),
        L("04-store-checklist", 4, 40, "قائمة المتجر", "Store checklist", "قبل الرفع.", "Before upload.",
          "الصور والأذونات والسياسات جزء من التسليم.", "Assets, permissions, and policies are part of shipping.",
          [["privacy", "وضّح البيانات المجمّعة.", "Privacy", "Disclose collected data."],
           ["permissions", "اطلب الأقل الضروري.", "Permissions", "Ask for the minimum."]],
          "// Checklist: icons, screenshots, privacy text, crash-free smoke test"),
      ],
    },
  ],
});

export { flutterTrack, flutterStages };
