/**
 * Deep language-fundamentals tracks for AlefYa roadmap (Alef → Ya).
 */
import { stage } from "./expand.mjs";

function L(
  slug,
  order,
  duration,
  titleAr,
  titleEn,
  summaryAr,
  summaryEn,
  focusAr,
  focusEn,
  ideas,
  code,
  stack,
) {
  return {
    slug,
    order,
    duration,
    title: { ar: titleAr, en: titleEn },
    summary: { ar: summaryAr, en: summaryEn },
    focus: { ar: focusAr, en: focusEn },
    stack,
    ideas: ideas.map(([ta, ba, te, be]) => ({
      title: { ar: ta, en: te },
      body: { ar: ba, en: be },
    })),
    codeSource: code,
    faqs: [
      {
        q: {
          ar: `ما أهم نقطة في «${titleAr}»؟`,
          en: `What's the key point of “${titleEn}”?`,
        },
        a: {
          ar: "افهم النموذج الذهني ثم طبّق المثال — لا تحفظ الأسماء فقط.",
          en: "Lock the mental model, then practice — don't memorize names only.",
        },
      },
      {
        q: { ar: "هل أكمل للدرس التالي؟", en: "Can I move on?" },
        a: {
          ar: "بعد قائمة التحقق وامتحان المرحلة عندما يحين وقته.",
          en: "After the checklist — and the stage exam when due.",
        },
      },
    ],
    nextHint: {
      ar: "اتبع ترتيب المرحلة فقط.",
      en: "Stay in stage order.",
    },
  };
}

function buildTrack({ slug, order, title, tagline, description, color, hours, stages }) {
  const track = {
    slug,
    order,
    title,
    tagline,
    description,
    color,
    estimatedHours: hours,
    stages: stages.map((s) => s.slug),
  };
  const stageMap = {};
  for (const s of stages) {
    stageMap[s.slug] = stage(s.slug, s.order, s.title, s.description, s.lessons);
  }
  return [track, stageMap];
}

const idea = (ta, ba, te, be) => [ta, ba, te, be];

// ——— C# ———
export const [csharpTrack, csharpStages] = buildTrack({
  slug: "csharp",
  order: 20,
  title: { ar: "C# من الصفر", en: "C# from zero" },
  tagline: {
    ar: "أساسيات C# قبل ASP.NET",
    en: "C# foundations before ASP.NET",
  },
  description: {
    ar: "مسار لغة كامل: متغيرات، أنواع، تحكم، دوال، OOP، مجموعات، LINQ، أخطاء، async، ثم مشروع كونسول.",
    en: "Full language path: variables, types, control flow, methods, OOP, collections, LINQ, errors, async, then a console project.",
  },
  color: "#68217A",
  hours: 80,
  stages: [
    {
      slug: "01-start",
      order: 1,
      title: { ar: "البداية", en: "Getting started" },
      description: { ar: "لماذا C# وكيف تشغّل أول برنامج", en: "Why C# and your first program" },
      lessons: [
        L("01-why-csharp", 1, 35, "لماذا C#؟", "Why C#?", "أين تُستخدم وما علاقتها بـ .NET.", "Where it's used and how it relates to .NET.",
          "C# لغة خلفية قوية مرتبطة بمنصة .NET.", "C# is a strong backend language on the .NET platform.",
          [idea("منصة .NET", "تشغّل C# على ويندوز ولينكس مع مكتبات غنية.", ".NET platform", "Runs C# on Windows/Linux with a rich BCL."),
           idea("سوق العمل", "مطلوبة في الشركات وASP.NET Core.", "Jobs", "In demand with ASP.NET Core backends.")],
          "Console.WriteLine(\"Hello AlefYa\");", "csharp"),
        L("02-first-program", 2, 40, "أول برنامج", "First program", "main، الطباعة، التشغيل.", "main, print, run.",
          "كل تطبيق يبدأ من نقطة دخول واضحة.", "Every app needs a clear entry point.",
          [idea("Main", "نقطة الدخول الافتراضية.", "Main", "Default entry point."),
           idea("Console", "إدخال/إخراج بسيط للتعلّم.", "Console", "Simple I/O for learning.")],
          "Console.WriteLine(1 + 1);", "csharp"),
        L("03-variables", 3, 45, "المتحولات", "Variables", "تعريف، تسمية، إسناد.", "Declare, name, assign.",
          "المتحول يخزّن قيمة يمكن قراءتها أو تغييرها.", "A variable stores a value you can read or change.",
          [idea("التصريح", "حدد النوع أو دع المترجم يستنتج.", "Declaration", "Specify a type or let the compiler infer."),
           idea("التسمية", "أسماء واضحة أفضل من اختصارات غامضة.", "Naming", "Clear names beat cryptic abbreviations.")],
          "int age = 20;\nvar name = \"Ahmad\";", "csharp"),
      ],
    },
    {
      slug: "02-types",
      order: 2,
      title: { ar: "الأنواع", en: "Types" },
      description: { ar: "أرقام، نصوص، منطقي، null", en: "Numbers, strings, bool, null" },
      lessons: [
        L("01-numbers", 1, 40, "الأرقام", "Numbers", "int، double، العمليات.", "int, double, operators.",
          "اختر نوعاً يناسب دقة الحساب.", "Pick a numeric type that matches precision needs.",
          [idea("int", "أعداد صحيحة للعدّ والفهارس.", "int", "Whole numbers for counts and indexes."),
           idea("double", "كسور للقيم الحقيقية.", "double", "Fractional real values.")],
          "double price = 19.99;\nint qty = 3;", "csharp"),
        L("02-strings-bool", 2, 40, "النصوص والمنطقي", "Strings & bool", "string، bool، الشروط البسيطة.", "string, bool, simple conditions.",
          "النصوص والمنطق أساس كل قرار في البرنامج.", "Text and logic drive every decision.",
          [idea("string", "تسلسل أحرف — انتبه للفارغ.", "string", "Character sequences — watch empty cases."),
           idea("bool", "صح/خطأ فقط.", "bool", "True/false only.")],
          "bool ok = name.Length > 0;", "csharp"),
        L("03-null-nullable", 3, 40, "null والأنواع القابلة للإلغاء", "Null & nullable", "متى تكون القيمة غائبة.", "When a value is missing.",
          "null يعني غياب قيمة — تعامل معه صراحة.", "null means missing — handle it explicitly.",
          [idea("Nullable", "int? يسمح بغياب الرقم.", "Nullable", "int? allows a missing number."),
           idea("??", "قيمة بديلة عند null.", "??", "Fallback when null.")],
          "int? score = null;\nvar v = score ?? 0;", "csharp"),
      ],
    },
    {
      slug: "03-control",
      order: 3,
      title: { ar: "التحكم", en: "Control flow" },
      description: { ar: "شروط وحلقات", en: "Branches and loops" },
      lessons: [
        L("01-if-switch", 1, 45, "if و switch", "if & switch", "تفرعات القرار.", "Decision branches.",
          "كل شرط يجب أن يغطي الحالة الحدّية.", "Every branch should cover edge cases.",
          [idea("if/else", "مسارات واضحة.", "if/else", "Clear paths."),
           idea("switch", "حالات متعددة لنفس القيمة.", "switch", "Many cases for one value.")],
          "if (age >= 18) Console.WriteLine(\"adult\");", "csharp"),
        L("02-loops", 2, 45, "الحلقات", "Loops", "for، while، foreach.", "for, while, foreach.",
          "الحلقة تكرر عملاً حتى شرط التوقف.", "Loops repeat work until a stop condition.",
          [idea("for", "عدّاد معروف.", "for", "Known counter."),
           idea("foreach", "مرور على مجموعة.", "foreach", "Walk a collection.")],
          "for (var i = 0; i < 3; i++) Console.WriteLine(i);", "csharp"),
        L("03-break-continue", 3, 35, "break و continue", "break & continue", "إيقاف أو تخطّي دورة.", "Stop or skip an iteration.",
          "استخدمها لتقليل التعقيد لا لإخفاء المنطق.", "Use them to reduce complexity, not hide logic.",
          [idea("break", "اخرج من الحلقة.", "break", "Exit the loop."),
           idea("continue", "انتقل للدورة التالية.", "continue", "Skip to next iteration.")],
          "if (i == 2) continue;", "csharp"),
      ],
    },
    {
      slug: "04-methods",
      order: 4,
      title: { ar: "الدوال", en: "Methods" },
      description: { ar: "إعادة الاستخدام والوسائط", en: "Reuse and parameters" },
      lessons: [
        L("01-methods-basics", 1, 45, "تعريف الدالة", "Defining methods", "إرجاع، معاملات، void.", "Return, params, void.",
          "الدالة تعزل مسؤولية واحدة قابلة للاختبار.", "A method isolates one testable responsibility.",
          [idea("return", "أعِد نتيجة.", "return", "Give back a result."),
           idea("void", "نفّذ بدون إرجاع.", "void", "Run with no return value.")],
          "int Add(int a, int b) => a + b;", "csharp"),
        L("02-overloads-defaults", 2, 40, "التحميل الزائد والافتراضي", "Overloads & defaults", "نفس الاسم بمعاملات مختلفة.", "Same name, different params.",
          "لا تكثر التحميل الزائد بلا حاجة.", "Don't overload without need.",
          [idea("overload", "توقيعات متعددة.", "overload", "Multiple signatures."),
           idea("optional", "معامل اختياري.", "optional", "Optional parameter.")],
          "void Log(string msg, bool verbose = false) { }", "csharp"),
        L("03-scope", 3, 35, "نطاق المتغيرات", "Variable scope", "محلي مقابل حقل.", "Local vs field.",
          "ضيّق النطاق قدر الإمكان.", "Keep scope as narrow as possible.",
          [idea("local", "يعيش داخل الكتلة.", "local", "Lives inside the block."),
           idea("field", "حالة الكائن.", "field", "Object state.")],
          "void Demo() { int x = 1; }", "csharp"),
      ],
    },
    {
      slug: "05-oop",
      order: 5,
      title: { ar: "البرمجة كائنية التوجه", en: "OOP" },
      description: { ar: "كائنات، تغليف، وراثة", en: "Objects, encapsulation, inheritance" },
      lessons: [
        L("01-classes-objects", 1, 45, "الكلاسات والكائنات", "Classes & objects", "قالب مقابل نسخة.", "Blueprint vs instance.",
          "الكلاس يصف الشكل؛ الكائن يحمل الحالة.", "A class describes shape; an object holds state.",
          [idea("class", "التعريف.", "class", "The definition."),
           idea("new", "إنشاء نسخة.", "new", "Create an instance.")],
          "class User { public string Name { get; set; } }", "csharp"),
        L("02-encapsulation", 2, 40, "التغليف", "Encapsulation", "private وخصائص.", "private and properties.",
          "احمِ الحالة خلف واجهة واضحة.", "Protect state behind a clear interface.",
          [idea("private", "إخفاء التفاصيل.", "private", "Hide details."),
           idea("property", "get/set مضبوط.", "property", "Controlled get/set.")],
          "private int _age; public int Age => _age;", "csharp"),
        L("03-inheritance-interfaces", 3, 45, "الوراثة والواجهات", "Inheritance & interfaces", "إعادة استخدام العقود.", "Reuse and contracts.",
          "فضّل التركيب عندما يكفي.", "Prefer composition when enough.",
          [idea("base", "وراثة السلوك.", "base", "Inherit behavior."),
           idea("interface", "عقد بدون تنفيذ.", "interface", "Contract without implementation.")],
          "interface IClock { DateTime Now(); }", "csharp"),
      ],
    },
    {
      slug: "06-collections-linq",
      order: 6,
      title: { ar: "المجموعات و LINQ", en: "Collections & LINQ" },
      description: { ar: "List وفلترة", en: "List and filtering" },
      lessons: [
        L("01-list-dict", 1, 40, "List و Dictionary", "List & Dictionary", "تخزين متسلسل ومفتاحي.", "Sequential and keyed storage.",
          "اختر البنية حسب نمط الوصول.", "Pick a structure by access pattern.",
          [idea("List", "ترتيب وفهرس.", "List", "Order and index."),
           idea("Dictionary", "بحث بمفتاح.", "Dictionary", "Lookup by key.")],
          "var nums = new List<int> { 1, 2, 3 };", "csharp"),
        L("02-linq-basics", 2, 45, "أساسيات LINQ", "LINQ basics", "Where، Select، Count.", "Where, Select, Count.",
          "LINQ يصف الاستعلام لا خطوات الحلقة يدوياً.", "LINQ describes the query, not manual loops.",
          [idea("Where", "تصفية.", "Where", "Filter."),
           idea("Select", "تحويل.", "Select", "Project.")],
          "var evens = nums.Where(n => n % 2 == 0);", "csharp"),
        L("03-linq-practice", 3, 40, "تمرين LINQ", "LINQ practice", "سلسلة عمليات قصيرة.", "Short operation chains.",
          "اطلب نتيجة واضحة ثم اكتب السلسلة.", "State the result, then write the chain.",
          [idea("Count", "عدّ المطابق.", "Count", "Count matches."),
           idea("FirstOrDefault", "أول عنصر أو افتراضي.", "FirstOrDefault", "First or default.")],
          "var n = nums.Count(x => x > 1);", "csharp"),
      ],
    },
    {
      slug: "07-errors-async",
      order: 7,
      title: { ar: "الأخطاء و async", en: "Errors & async" },
      description: { ar: "try/catch و Task", en: "try/catch and Task" },
      lessons: [
        L("01-exceptions", 1, 40, "الاستثناءات", "Exceptions", "try، catch، finally.", "try, catch, finally.",
          "التقط ما تستطيع إصلاحه فقط.", "Catch only what you can handle.",
          [idea("try/catch", "حاصر الفشل المتوقع.", "try/catch", "Contain expected failure."),
           idea("finally", "تنظيف دائماً.", "finally", "Always clean up.")],
          "try { File.ReadAllText(\"x\"); } catch (IOException ex) { }", "csharp"),
        L("02-async-await", 2, 45, "async/await", "async/await", "عمليات غير متزامنة.", "Asynchronous work.",
          "لا تحجب الخيط على I/O طويل.", "Don't block a thread on long I/O.",
          [idea("Task", "عمل مستقبلي.", "Task", "Future work."),
           idea("await", "انتظر النتيجة.", "await", "Await the result.")],
          "async Task<string> LoadAsync() => await File.ReadAllTextAsync(\"a.txt\");", "csharp"),
        L("03-async-pitfalls", 3, 35, "أخطاء async الشائعة", "Async pitfalls", "deadlock و fire-and-forget.", "Deadlocks and fire-and-forget.",
          "افهم تدفق الانتظار قبل الإنتاج.", "Understand await flow before production.",
          [idea("async void", "تجنّبه إلا في معالجات أحداث.", "async void", "Avoid except event handlers."),
           idea("ConfigureAwait", "مهم في مكتبات UI أحياناً.", "ConfigureAwait", "Sometimes critical in UI libs.")],
          "await Task.Delay(10);", "csharp"),
      ],
    },
    {
      slug: "08-project",
      order: 8,
      title: { ar: "مشروع كونسول", en: "Console project" },
      description: { ar: "طبّق ما تعلمته", en: "Apply what you learned" },
      lessons: [
        L("01-design", 1, 40, "تصميم المشروع", "Project design", "قائمة مهام نصية.", "Text todo list.",
          "حدد المدخلات والمخرجات قبل الكود.", "Define inputs/outputs before coding.",
          [idea("المتطلبات", "إضافة، عرض، حذف.", "Requirements", "Add, list, delete."),
           idea("النموذج", "كلاس TaskItem.", "Model", "TaskItem class.")],
          "// Plan: menu loop + List<TaskItem>", "csharp"),
        L("02-implement", 2, 50, "التنفيذ", "Implement", "قائمة وحفظ بسيط.", "List and simple persistence.",
          "نفّذ أصغر نسخة تعمل.", "Ship the smallest working version.",
          [idea("القائمة", "List في الذاكرة.", "List", "In-memory List."),
           idea("القائمة النصية", "قراءة أوامر المستخدم.", "CLI menu", "Read user commands.")],
          "var items = new List<string>();", "csharp"),
        L("03-polish", 3, 40, "تحسين", "Polish", "تحقق من المدخلات وأخطاء.", "Validate input and errors.",
          "أضف رسائل فشل واضحة.", "Add clear failure messages.",
          [idea("validation", "ارفض الفارغ.", "validation", "Reject empty."),
           idea("ready", "جاهز لمسار ASP.NET.", "ready", "Ready for the ASP.NET track.")],
          "if (string.IsNullOrWhiteSpace(input)) return;", "csharp"),
      ],
    },
  ],
});

// ——— Dart ———
export const [dartTrack, dartStages] = buildTrack({
  slug: "dart",
  order: 21,
  title: { ar: "Dart من الصفر", en: "Dart from zero" },
  tagline: { ar: "لغة Flutter قبل الواجهات", en: "Flutter's language before UI" },
  description: {
    ar: "أساسيات Dart: أنواع، null safety، دوال، OOP، مجموعات، async، ثم مشروع صغير.",
    en: "Dart foundations: types, null safety, functions, OOP, collections, async, then a small project.",
  },
  color: "#0175C2",
  hours: 60,
  stages: [
    {
      slug: "01-basics",
      order: 1,
      title: { ar: "الأساسيات", en: "Basics" },
      description: { ar: "لماذا Dart وأول كود", en: "Why Dart and first code" },
      lessons: [
        L("01-why-dart", 1, 30, "لماذا Dart؟", "Why Dart?", "علاقتها بـ Flutter.", "How it relates to Flutter.",
          "Dart هي لغة Flutter الرسمية.", "Dart is Flutter's official language.",
          [idea("منصة واحدة", "نفس اللغة للجوال والويب.", "One language", "Same language for mobile and web."),
           idea("null safety", "تقليل أعطال null.", "null safety", "Fewer null crashes.")],
          "void main() => print('hi');", "dart"),
        L("02-variables-types", 2, 40, "متغيرات وأنواع", "Variables & types", "var، final، const.", "var, final, const.",
          "ميّز ما يتغير عما يثبت.", "Separate mutable from fixed.",
          [idea("final", "مرة واحدة.", "final", "Assign once."),
           idea("const", "ثابت وقت الترجمة.", "const", "Compile-time constant.")],
          "final name = 'Alef';\nint n = 3;", "dart"),
        L("03-null-safety", 3, 40, "Null safety", "Null safety", "؟ و !! و ?.", "?, !!, and ?..",
          "اجعل الغياب صريحاً في النوع.", "Make absence explicit in the type.",
          [idea("String?", "قد تكون null.", "String?", "May be null."),
           idea("?", "وصول آمن.", "?", "Safe access.")],
          "String? s;\nprint(s?.length);", "dart"),
      ],
    },
    {
      slug: "02-control-functions",
      order: 2,
      title: { ar: "تحكم ودوال", en: "Control & functions" },
      description: { ar: "شروط، حلقات، دوال", en: "Branches, loops, functions" },
      lessons: [
        L("01-if-loops", 1, 40, "شروط وحلقات", "If & loops", "if، for، while.", "if, for, while.",
          "غطِّ الحالات الحدّية في كل فرع.", "Cover edges in every branch.",
          [idea("for", "عدّاد.", "for", "Counter."),
           idea("for-in", "على مجموعة.", "for-in", "Over a collection.")],
          "for (final x in [1,2]) print(x);", "dart"),
        L("02-functions", 2, 40, "الدوال", "Functions", "معاملات مسماة واختيارية.", "Named and optional params.",
          "الدوال القصيرة أوضح.", "Short functions stay clear.",
          [idea("named", " وضوح الاستدعاء.", "named", "Clear call sites."),
           idea("=>", "تعبير مختصر.", "=>", "Expression body.")],
          "int add(int a, {int b = 0}) => a + b;", "dart"),
        L("03-collections", 3, 40, "المجموعات", "Collections", "List، Map، Set.", "List, Map, Set.",
          "اختر البنية حسب الاستخدام.", "Pick by use case.",
          [idea("List", "ترتيب.", "List", "Order."),
           idea("Map", "مفتاح→قيمة.", "Map", "Key→value.")],
          "final m = {'a': 1};", "dart"),
      ],
    },
    {
      slug: "03-oop-async",
      order: 3,
      title: { ar: "OOP و async", en: "OOP & async" },
      description: { ar: "كلاسات و Future", en: "Classes and Future" },
      lessons: [
        L("01-classes", 1, 40, "الكلاسات", "Classes", "حقول، منشئ، methods.", "Fields, ctor, methods.",
          "نمذج البيانات ككائنات.", "Model data as objects.",
          [idea("constructor", "تهيئة الحالة.", "constructor", "Init state."),
           idea("method", "سلوك الكائن.", "method", "Object behavior.")],
          "class User { User(this.id); final String id; }", "dart"),
        L("02-async", 2, 45, "Future و async", "Future & async", "await للـ I/O.", "await for I/O.",
          "لا تحجب واجهة المستخدم على الانتظار.", "Don't block UI on waiting.",
          [idea("Future", "نتيجة لاحقة.", "Future", "Later result."),
           idea("async", "دالة تنتظر.", "async", "Function that awaits.")],
          "Future<void> load() async { await Future.delayed(Duration(seconds: 1)); }", "dart"),
        L("03-mini-project", 3, 45, "مشروع صغير", "Mini project", "قائمة مهام نصية بـ Dart.", "CLI todo in Dart.",
          "طبّق الأنواع والدوال والمجموعات.", "Apply types, functions, collections.",
          [idea("menu", "حلقة أوامر.", "menu", "Command loop."),
           idea("ready", "جاهز لمسار Flutter.", "ready", "Ready for Flutter track.")],
          "final todos = <String>[];", "dart"),
      ],
    },
  ],
});

function langStagesJsLike(stack, titlePrefix) {
  return [
    {
      slug: "01-start",
      order: 1,
      title: { ar: "البداية", en: "Start" },
      description: { ar: `مدخل ${titlePrefix}`, en: `${titlePrefix} intro` },
      lessons: [
        L("01-why", 1, 35, `لماذا ${titlePrefix}؟`, `Why ${titlePrefix}?`, "أين تُستخدم في الويب.", "Where it's used on the web.",
          `${titlePrefix} أساس الواجهة والتفاعل في المتصفح أو الأدوات.`, `${titlePrefix} underpins web UI and tooling.`,
          [idea("المنصة", "المتصفح أو Node.", "Platform", "Browser or Node."),
           idea("الطلب", "أساس الفرونت والموبايل الهجين.", "Demand", "Core for frontend and hybrid mobile.")],
          stack === "typescript" ? "const x: number = 1;" : "const x = 1;", stack),
        L("02-values-vars", 2, 40, "قيم ومتغيرات", "Values & variables", "let، const، أنواع أساسية.", "let, const, primitive types.",
          "const افتراضياً؛ let عند الحاجة للتغيير.", "Default to const; use let when mutation is needed.",
          [idea("const", "مرجع ثابت.", "const", "Fixed binding."),
           idea("types", stack === "typescript" ? "أنواع صريحة." : "أنواع ديناميكية.", "types", stack === "typescript" ? "Explicit types." : "Dynamic types.")],
          stack === "typescript" ? "let n: number = 0;" : "let n = 0;", stack),
        L("03-operators", 3, 35, "العمليات", "Operators", "حسابية ومنطقية.", "Arithmetic and logic.",
          "افهم الأولوية والحالات الحدّية.", "Know precedence and edge cases.",
          [idea("===", "مساواة صارمة.", "===", "Strict equality."),
           idea("&& ||", "منطق قصير الدائرة.", "&& ||", "Short-circuit logic.")],
          "const ok = n > 0 && n < 10;", stack),
      ],
    },
    {
      slug: "02-control-functions",
      order: 2,
      title: { ar: "تحكم ودوال", en: "Control & functions" },
      description: { ar: "شروط وحلقات ودوال", en: "Branches, loops, functions" },
      lessons: [
        L("01-if-loops", 1, 40, "شروط وحلقات", "If & loops", "if، for، while.", "if, for, while.",
          "غطِّ الفراغ والقيم غير المتوقعة.", "Cover empty and unexpected values.",
          [idea("for...of", "على المصفوفات.", "for...of", "Over arrays."),
           idea("while", "شرط غير معروف الطول مسبقاً.", "while", "Unknown length ahead of time.")],
          "for (const x of [1,2]) console.log(x);", stack),
        L("02-functions", 2, 40, "الدوال", "Functions", "تصريح، سهم، معاملات.", "Declaration, arrow, params.",
          "دالة واحدة = مسؤولية واحدة.", "One function = one responsibility.",
          [idea("arrow", "مختصر وواضح.", "arrow", "Short and clear."),
           idea("default", "قيمة افتراضية.", "default", "Default value.")],
          "const add = (a, b = 0) => a + b;", stack),
        L("03-arrays-objects", 3, 45, "مصفوفات وكائنات", "Arrays & objects", "map، filter، مفاتيح.", "map, filter, keys.",
          "البيانات غالباً مصفوفة من كائنات.", "Data is often an array of objects.",
          [idea("map/filter", "تحويل دون حلقات يدوية معقّدة.", "map/filter", "Transform without messy loops."),
           idea("object", "حقول مسماة.", "object", "Named fields.")],
          "const ages = users.map(u => u.age);", stack),
      ],
    },
    {
      slug: "03-async-modules",
      order: 3,
      title: { ar: "Async والوحدات", en: "Async & modules" },
      description: { ar: "Promises و import", en: "Promises and import" },
      lessons: [
        L("01-promises", 1, 45, "Promises", "Promises", "then و catch.", "then and catch.",
          "الوعد يمثل نتيجة لاحقة.", "A promise represents a later result.",
          [idea("pending", "قيد الانتظار.", "pending", "Waiting."),
           idea("catch", "التقط الفشل.", "catch", "Catch failure.")],
          "Promise.resolve(1).then(console.log);", stack),
        L("02-async-await", 2, 40, "async/await", "async/await", "كتابة متسلسلة أوضح.", "Clearer sequential style.",
          "انتظر I/O دون حجب الفهم.", "Await I/O without blocking understanding.",
          [idea("await", "انتظر الوعد.", "await", "Await the promise."),
           idea("try/catch", "أخطاء async.", "try/catch", "Async errors.")],
          "async function load() { return await fetch('/x'); }", stack),
        L("03-modules", 3, 35, "الوحدات", "Modules", "import/export.", "import/export.",
          "قسّم الملف إلى وحدات صغيرة.", "Split into small modules.",
          [idea("export", "شارك رمزاً.", "export", "Share a symbol."),
           idea("import", "استهلك وحدة.", "import", "Consume a module.")],
          "export function hi() { return 'hi'; }", stack),
      ],
    },
    {
      slug: "04-project",
      order: 4,
      title: { ar: "مشروع صغير", en: "Mini project" },
      description: { ar: "تطبيق ما تعلمته", en: "Apply what you learned" },
      lessons: [
        L("01-design", 1, 35, "التصميم", "Design", "قائمة مهام بسيطة.", "Simple todo.",
          "حدد الحالات قبل الواجهة.", "Define states before UI.",
          [idea("state", "قائمة العناصر.", "state", "Item list."),
           idea("actions", "إضافة/حذف.", "actions", "Add/remove.")],
          "// todos: string[]", stack),
        L("02-build", 2, 45, "البناء", "Build", "منطق القائمة.", "List logic.",
          "نفّذ أصغر نسخة.", "Build the smallest version.",
          [idea("add", "ادفع عنصراً.", "add", "Push an item."),
           idea("remove", "احذف بفهرس.", "remove", "Remove by index.")],
          "const todos = []; todos.push('learn');", stack),
        L("03-ready", 3, 30, "الجاهزية", "Ready", "راجع المعيار ثم الإطار.", "Review the bar, then the framework.",
          "أنت جاهز لمسار الإطار التالي.", "You're ready for the next framework track.",
          [idea("checklist", "أتمّ القوائم.", "checklist", "Finish checklists."),
           idea("next", "انتقل للإطار.", "next", "Move to the framework.")],
          "console.log('ready');", stack),
      ],
    },
  ];
}

export const [javascriptTrack, javascriptStages] = buildTrack({
  slug: "javascript",
  order: 22,
  title: { ar: "JavaScript من الصفر", en: "JavaScript from zero" },
  tagline: { ar: "لغة الويب قبل React و Node", en: "The web language before React & Node" },
  description: {
    ar: "أساسيات JS كاملة: قيم، تحكم، دوال، بيانات، async، وحدات، مشروع.",
    en: "Full JS foundations: values, control, functions, data, async, modules, project.",
  },
  color: "#F7DF1E",
  hours: 70,
  stages: langStagesJsLike("javascript", "JavaScript"),
});

export const [typescriptTrack, typescriptStages] = buildTrack({
  slug: "typescript",
  order: 23,
  title: { ar: "TypeScript من الصفر", en: "TypeScript from zero" },
  tagline: { ar: "أنواع أقوى قبل React/Angular", en: "Stronger types before React/Angular" },
  description: {
    ar: "مسار TypeScript للمبتدئين مع أنواع، دوال، ووحدات قبل أطر الواجهة.",
    en: "Beginner TypeScript path with types, functions, and modules before UI frameworks.",
  },
  color: "#3178C6",
  hours: 70,
  stages: langStagesJsLike("typescript", "TypeScript"),
});

export const [pythonTrack, pythonStages] = buildTrack({
  slug: "python",
  order: 24,
  title: { ar: "Python من الصفر", en: "Python from zero" },
  tagline: { ar: "أساسيات Python قبل الـ APIs", en: "Python foundations before APIs" },
  description: {
    ar: "لغة Python من المتغيرات حتى مشروع صغير ثم الانتقال لإطار الويب.",
    en: "Python from variables through a mini project, then into web frameworks.",
  },
  color: "#3776AB",
  hours: 70,
  stages: [
    {
      slug: "01-start",
      order: 1,
      title: { ar: "البداية", en: "Start" },
      description: { ar: "لماذا Python", en: "Why Python" },
      lessons: [
        L("01-why-python", 1, 30, "لماذا Python؟", "Why Python?", "سهولة القراءة وسوق العمل.", "Readability and jobs.",
          "Python ممتازة للبداية وللخلفية وعلوم البيانات.", "Python is great for beginners, backends, and data.",
          [idea("البساطة", "صياغة قريبة من الإنجليزية.", "Simplicity", "Near-English syntax."),
           idea("النظام البيئي", "مكتبات كثيرة.", "Ecosystem", "Huge libraries.")],
          "print('hello')", "python"),
        L("02-variables", 2, 40, "المتحولات والأنواع", "Variables & types", "int، str، bool، list.", "int, str, bool, list.",
          "النوع يحدد العمليات المتاحة.", "Type determines available operations.",
          [idea("dynamic", "النوع وقت التشغيل.", "dynamic", "Runtime typing."),
           idea("list", "تسلسل قابل للتغيير.", "list", "Mutable sequence.")],
          "age = 20\nnames = ['a', 'b']", "python"),
        L("03-control", 3, 40, "التحكم", "Control flow", "if و for.", "if and for.",
          "المسافات البادئة جزء من الصيغة.", "Indentation is syntax.",
          [idea("indent", "كتل بالكود.", "indent", "Blocks by indent."),
           idea("for", "على iterable.", "for", "Over iterables.")],
          "for n in names:\n  print(n)", "python"),
      ],
    },
    {
      slug: "02-functions-data",
      order: 2,
      title: { ar: "دوال وبيانات", en: "Functions & data" },
      description: { ar: "def و dict", en: "def and dict" },
      lessons: [
        L("01-functions", 1, 40, "الدوال", "Functions", "معاملات وقيم افتراضية.", "Params and defaults.",
          "اجعل الدالة قصيرة وواضحة.", "Keep functions short and clear.",
          [idea("def", "تعريف.", "def", "Definition."),
           idea("return", "إرجاع.", "return", "Return.")],
          "def add(a, b=0):\n  return a + b", "python"),
        L("02-dicts", 2, 40, "القواميس", "Dictionaries", "مفتاح→قيمة.", "Key→value.",
          "dict أساس JSON في بايثون.", "dict is Python's JSON cousin.",
          [idea("get", "وصول آمن.", "get", "Safe access."),
           idea("keys", "المفاتيح.", "keys", "Keys.")],
          "user = {'id': 1, 'name': 'A'}", "python"),
        L("03-errors", 3, 35, "الأخطاء", "Errors", "try/except.", "try/except.",
          "التقط أخطاء متوقعة فقط.", "Catch expected errors only.",
          [idea("except", "تعامل مع الفشل.", "except", "Handle failure."),
           idea("finally", "تنظيف.", "finally", "Cleanup.")],
          "try:\n  int('x')\nexcept ValueError:\n  pass", "python"),
      ],
    },
    {
      slug: "03-async-project",
      order: 3,
      title: { ar: "مشروع", en: "Project" },
      description: { ar: "تطبيق عملي", en: "Hands-on" },
      lessons: [
        L("01-files", 1, 40, "الملفات", "Files", "قراءة/كتابة نص.", "Read/write text.",
          "أغلق الموارد أو استخدم with.", "Close resources or use with.",
          [idea("with", "إدارة السياق.", "with", "Context manager."),
           idea("path", "مسار الملف.", "path", "File path.")],
          "with open('a.txt') as f:\n  print(f.read())", "python"),
        L("02-mini-api-mindset", 2, 40, "عقلية الـ API", "API mindset", "طلب واستجابة قبل FastAPI.", "Request/response before FastAPI.",
          "افصل المدخل عن المنطق عن المخرج.", "Separate input, logic, output.",
          [idea("request", "بيانات داخلة.", "request", "Inbound data."),
           idea("response", "نتيجة خارجة.", "response", "Outbound result.")],
          "def handle(payload): return {'ok': True}", "python"),
        L("03-ready", 3, 30, "جاهز للإطار", "Ready for framework", "انتقل لمسار الويب.", "Move to the web track.",
          "أساسيات اللغة كافية لبدء FastAPI.", "Language basics are enough to start FastAPI.",
          [idea("review", "راجع القوائم.", "review", "Review checklists."),
           idea("next", "مرحلة الويب التالية.", "next", "Next: web stage.")],
          "print('ready')", "python"),
      ],
    },
    {
      slug: "04-web-fastapi",
      order: 4,
      title: { ar: "مدخل FastAPI", en: "FastAPI intro" },
      description: { ar: "أول API بعد أساسيات اللغة", en: "First API after language basics" },
      lessons: [
        L("01-why-fastapi", 1, 35, "لماذا FastAPI؟", "Why FastAPI?", "سرعة ووثائق تلقائية.", "Speed and auto docs.",
          "FastAPI يبني APIs حديثة بـ Python.", "FastAPI builds modern Python APIs.",
          [idea("docs", "OpenAPI تلقائي.", "docs", "Automatic OpenAPI."),
           idea("typing", "أنواع تساعد التحقق.", "typing", "Types aid validation.")],
          "from fastapi import FastAPI\napp = FastAPI()", "python"),
        L("02-first-route", 2, 40, "أول مسار", "First route", "GET بسيط.", "Simple GET.",
          "المسار يربط URL بدالة.", "A route binds a URL to a function.",
          [idea("@app.get", "مزخرف المسار.", "@app.get", "Route decorator."),
           idea("return", "JSON تلقائياً.", "return", "JSON automatically.")],
          "@app.get('/health')\ndef health():\n  return {'ok': True}", "python"),
        L("03-models", 3, 40, "نماذج الطلب", "Request models", "Pydantic.", "Pydantic.",
          "التحقق من المدخلات قبل المنطق.", "Validate input before logic.",
          [idea("BaseModel", "شكل البيانات.", "BaseModel", "Data shape."),
           idea("validation", "رفض الخاطئ.", "validation", "Reject bad input.")],
          "class TrackIn(BaseModel):\n  slug: str\n  title: str", "python"),
      ],
    },
  ],
});

export const languageTrackBundles = [
  [csharpTrack, csharpStages],
  [dartTrack, dartStages],
  [javascriptTrack, javascriptStages],
  [typescriptTrack, typescriptStages],
  [pythonTrack, pythonStages],
];
