/**
 * Popular high-demand tracks for AlefYa categories.
 * Flutter + 2 tracks per other category section.
 */
import { stage } from "./expand.mjs";

function L(slug, order, duration, titleAr, titleEn, summaryAr, summaryEn, focusAr, focusEn, ideas, code, stack = "javascript") {
  return {
    slug,
    order,
    duration,
    title: { ar: titleAr, en: titleEn },
    summary: { ar: summaryAr, en: summaryEn },
    focus: { ar: focusAr, en: focusEn },
    stack,
    ideas: ideas.map(([ta, ba, te, be]) => ({
      title: { ar: ta, en: te },
      body: { ar: ba, en: be },
    })),
    codeSource: code,
    faqs: [
      {
        q: { ar: `ما أهم نقطة في «${titleAr}»؟`, en: `What's the key point of “${titleEn}”?` },
        a: {
          ar: `افهم النموذج الذهني أولاً ثم طبّق المثال. هذا أساس مسار ألف ياء.`,
          en: `Lock the mental model first, then practice the example. That's the AlefYa approach.`,
        },
      },
      {
        q: { ar: "هل أحتاج أدوات خارج الموقع؟", en: "Do I need tools outside the site?" },
        a: {
          ar: "المفاهيم والتمارين هنا كافية للفهم؛ نفّذ محلياً عندما يطلب الدرس ذلك.",
          en: "Concepts and exercises here are enough to learn; run locally when the lesson asks.",
        },
      },
      {
        q: { ar: "كيف أتأكد أنني جاهز؟", en: "How do I know I'm ready?" },
        a: {
          ar: "أنهِ قائمة التحقق واشرح الفكرة لزميل بدون نسخ أعمى.",
          en: "Finish the checklist and explain the idea without blind copying.",
        },
      },
      {
        q: { ar: "ماذا بعد هذا الدرس؟", en: "What's next?" },
        a: {
          ar: "اتبع ترتيب المرحلة فقط — كل درس يبني على السابق.",
          en: "Follow the stage order only — each lesson builds on the previous.",
        },
      },
    ],
    nextHint: {
      ar: "انتقل للدرس التالي في نفس المرحلة بالترتيب.",
      en: "Continue to the next lesson in this stage, in order.",
    },
  };
}

function buildTrack({ slug, order, title, tagline, description, color, hours, stages }) {
  const track = {
    slug,
    order,
    title,
    tagline,
    description,
    color,
    estimatedHours: hours,
    stages: stages.map((s) => s.slug),
  };
  const stageMap = {};
  for (const s of stages) {
    stageMap[s.slug] = stage(s.slug, s.order, s.title, s.description, s.lessons);
  }
  return [track, stageMap];
}

// ——— Flutter ———
const [flutterTrack, flutterStages] = buildTrack({
  slug: "flutter",
  order: 6,
  title: { ar: "Flutter", en: "Flutter" },
  tagline: {
    ar: "من Dart حتى تطبيق جوال متعدد المنصات",
    en: "From Dart to a cross-platform mobile app",
  },
  description: {
    ar: "مسار Flutter الأشهر عالمياً لبناء iOS وAndroid بقاعدة كود واحدة: Dart، Widgets، الحالة، التنقل، ثم مشروع.",
    en: "The world's most popular path for one codebase on iOS & Android: Dart, widgets, state, navigation, then a project.",
  },
  color: "#02569B",
  hours: 100,
  stages: [
    {
      slug: "01-dart",
      order: 1,
      title: { ar: "أساسيات Dart", en: "Dart foundations" },
      description: { ar: "لغة Flutter", en: "Flutter's language" },
      lessons: [
        L("01-why-flutter", 1, 40, "لماذا Flutter؟", "Why Flutter?", "أين يُستخدم ولماذا يُطلب كثيراً.", "Where it's used and why demand is high.",
          "Flutter من أكثر أطر الجوال بحثاً وتوظيفاً لأنه يوحّد iOS وAndroid.", "Flutter is among the most searched mobile stacks because it unifies iOS and Android.",
          [["منصة واحدة", "تطبيق واحد يعمل على منصتين مع أداء قريب من الأصلي عبر محرك الرسم.", "One codebase", "One app on two platforms with near-native performance via its rendering engine."],
           ["سوق العمل", "مطلوب في الشركات الناشئة والوكالات التي تريد سرعة تسليم.", "Job market", "In demand at startups and agencies that need fast delivery."]],
          "void main() {\n  print('Hello Flutter');\n}", "dart"),
        L("02-dart-syntax", 2, 45, "صيغة Dart", "Dart syntax", "متغيرات، دوال، null safety.", "Vars, functions, null safety.",
          "Dart هي أساس كل Widget — أتقنها قبل الواجهة.", "Dart underpins every widget — master it before UI.",
          [["Null safety", "الأنواع غير القابلة للـ null تقلّل أعطال الإنتاج.", "Null safety", "Non-nullable types cut a huge class of production crashes."],
           ["async", "Future وasync/await لكل I/O.", "async", "Future and async/await for every I/O path."]],
          "String greet(String? name) => 'Hi ${name ?? 'guest'}';", "dart"),
        L("03-classes-collections", 3, 45, "الفئات والمجموعات", "Classes & collections", "class، List، Map.", "class, List, Map.",
          "نماذج البيانات في Flutter تُبنى من classes ومجموعات.", "Flutter data models are classes and collections.",
          [["List وMap", "أساس القوائم والحالة.", "List & Map", "Core of lists and state."],
           ["Constructors", "named وfactory شائعان جداً.", "Constructors", "Named and factory constructors are everywhere."]],
          "class User {\n  final String id;\n  User(this.id);\n}", "dart"),
      ],
    },
    {
      slug: "02-widgets",
      order: 2,
      title: { ar: "Widgets", en: "Widgets" },
      description: { ar: "كل شيء Widget", en: "Everything is a widget" },
      lessons: [
        L("01-widget-tree", 1, 45, "شجرة الـ Widgets", "The widget tree", "Stateless مقابل Stateful.", "Stateless vs Stateful.",
          "فهم الشجرة يمنع أخطاء setState العشوائية.", "Understanding the tree prevents random setState bugs.",
          [["StatelessWidget", "UI يعتمد على المدخلات فقط.", "StatelessWidget", "UI depends only on inputs."],
           ["StatefulWidget", "حالة محلية تتغير مع التفاعل.", "StatefulWidget", "Local state that changes with interaction."]],
          "class Hello extends StatelessWidget {\n  const Hello({super.key});\n  @override\n  Widget build(BuildContext context) => const Text('AlefYa');\n}", "dart"),
        L("02-layout", 2, 45, "التخطيط", "Layout", "Row، Column، Expanded.", "Row, Column, Expanded.",
          "Flex layout هو يوميات مطوّر Flutter.", "Flex layout is daily Flutter work.",
          [["Column/Row", "المحاور الرئيسية للتوزيع.", "Column/Row", "Main axes for composition."],
           ["Expanded", "يملأ المساحة المتبقية بذكاء.", "Expanded", "Fills remaining space intelligently."]],
          "Column(children: [Text('A'), Text('B')])", "dart"),
        L("03-navigation", 3, 45, "التنقل", "Navigation", "Navigator وroutes.", "Navigator and routes.",
          "التنقل بين الشاشات أساس أي تطبيق.", "Screen navigation is foundational.",
          [["Navigator", "مكدس الشاشات.", "Navigator", "The screen stack."],
           ["named routes", "تنظيم أوضح للتطبيقات الكبيرة.", "Named routes", "Cleaner structure for larger apps."]],
          "Navigator.push(context, MaterialPageRoute(builder: (_) => NextPage()));", "dart"),
      ],
    },
    {
      slug: "03-state-project",
      order: 3,
      title: { ar: "الحالة ومشروع", en: "State & project" },
      description: { ar: "Provider/Riverpod ثم مشروع", en: "Provider/Riverpod then a project" },
      lessons: [
        L("01-setstate-limits", 1, 40, "حدود setState", "Limits of setState", "متى تتجاوز الحالة المحلية.", "When local state is not enough.",
          "التطبيقات الحقيقية تحتاج حالة مشتركة.", "Real apps need shared state.",
          [["رفع الحالة", "شارك البيانات بين الشاشات.", "Lifting state", "Share data across screens."],
           ["أنماط شائعة", "Provider وRiverpod وBloc.", "Common patterns", "Provider, Riverpod, and Bloc."]],
          "// prefer a state package for shared app state", "dart"),
        L("02-http", 2, 45, "HTTP والـ JSON", "HTTP & JSON", "جلب بيانات من API.", "Fetching from an API.",
          "معظم التطبيقات تتكلم مع خادم.", "Most apps talk to a server.",
          [["http/dio", "طلبات الشبكة.", "http/dio", "Network requests."],
           ["fromJson", "تحويل JSON لنماذج.", "fromJson", "Map JSON into models."]],
          "final res = await http.get(Uri.parse('https://api.example.com'));", "dart"),
        L("03-capstone", 3, 55, "مشروع تطبيقي", "Capstone project", "شاشة قائمة + تفاصيل.", "List + detail screens.",
          "اجمع Widgets والحالة والشبكة في تطبيق صغير.", "Combine widgets, state, and networking in a small app.",
          [["تصميم الشاشات", "قائمة ثم تفاصيل.", "Screen design", "List then detail."],
           ["تسليم", "اختبر على محاكٍ أو جهاز.", "Ship", "Test on emulator or device."]],
          "// Build a lessons list screen for AlefYa-style content", "dart"),
      ],
    },
  ],
});

// ——— Vue ———
const [vueTrack, vueStages] = buildTrack({
  slug: "vue",
  order: 7,
  title: { ar: "Vue.js", en: "Vue.js" },
  tagline: { ar: "إطار تقدّمي لواجهات ويب سريعة التعلم", en: "The progressive framework teams love to learn fast" },
  description: {
    ar: "Vue من أكثر أطر الواجهة بحثاً: Composition API، المكوّنات، Pinia، Vue Router، ثم مشروع.",
    en: "Vue is one of the most searched UI frameworks: Composition API, components, Pinia, Vue Router, then a project.",
  },
  color: "#42B883",
  hours: 85,
  stages: [
    {
      slug: "01-basics",
      order: 1,
      title: { ar: "أساسيات Vue", en: "Vue basics" },
      description: { ar: "التفاعلية والمكوّنات", en: "Reactivity and components" },
      lessons: [
        L("01-why-vue", 1, 40, "لماذا Vue؟", "Why Vue?", "سهولة التعلم وسوق العمل.", "Gentle learning curve and market demand.",
          "Vue يجمع بين بساطة البدء وقوة التطبيقات الكبيرة.", "Vue balances easy onboarding with power for large apps.",
          [["Progressive", "استخدم منه ما تحتاجه فقط.", "Progressive", "Adopt only what you need."],
           ["سوق", "شائع في الشركات والمنتجات المتوسطة.", "Market", "Common in companies and mid-size products."]],
          "createApp({ setup() { return { msg: 'AlefYa' } } }).mount('#app')", "javascript"),
        L("02-template-reactivity", 2, 45, "القوالب والتفاعلية", "Templates & reactivity", "ref وreactive.", "ref and reactive.",
          "التفاعلية هي قلب Vue.", "Reactivity is Vue's core.",
          [["ref", "قيم بدائية تفاعلية.", "ref", "Reactive primitives."],
           ["template", "ربط العرض بالحالة.", "template", "Bind UI to state."]],
          "const count = ref(0)\nfunction inc() { count.value++ }", "javascript"),
        L("03-components", 3, 45, "المكوّنات", "Components", "props وemit.", "props and emit.",
          "قسّم الواجهة لوحدات قابلة لإعادة الاستخدام.", "Split UI into reusable units.",
          [["props", "بيانات للأسفل.", "props", "Data downward."],
           ["emit", "أحداث للأعلى.", "emit", "Events upward."]],
          "defineProps<{ title: string }>()\nconst emit = defineEmits<{ save: [] }>()", "javascript"),
      ],
    },
    {
      slug: "02-router-state",
      order: 2,
      title: { ar: "Router وPinia", en: "Router & Pinia" },
      description: { ar: "التنقل والحالة العامة", en: "Routing and global state" },
      lessons: [
        L("01-vue-router", 1, 45, "Vue Router", "Vue Router", "مسارات وصفحات.", "Routes and pages.",
          "التطبيقات متعددة الصفحات تحتاج Router.", "Multi-page apps need a router.",
          [["routes", "تعريف المسارات.", "routes", "Declare routes."],
           ["navigation", "الانتقال برمجياً.", "navigation", "Programmatic navigation."]],
          "const router = createRouter({ history: createWebHistory(), routes })", "javascript"),
        L("02-pinia", 2, 45, "Pinia", "Pinia", "مخزن الحالة الرسمي.", "Official state store.",
          "Pinia هو المعيار الحالي لحالة Vue.", "Pinia is the current Vue state standard.",
          [["stores", "حالة مركزية.", "stores", "Central state."],
           ["actions", "تحديثات واضحة.", "actions", "Explicit updates."]],
          "export const useTrackStore = defineStore('tracks', { state: () => ({ started: [] }) })", "javascript"),
        L("03-project", 3, 50, "مشروع Vue", "Vue project", "لوحة مسارات بسيطة.", "A simple tracks board.",
          "اجمع المكوّنات والـ Router وPinia.", "Combine components, router, and Pinia.",
          [["هيكلة", "صفحات + متجر.", "Structure", "Pages + store."],
           ["تسليم", "ابنِ وشغّل محلياً.", "Ship", "Build and run locally."]],
          "// Vue SFC pages for category → track list", "javascript"),
      ],
    },
  ],
});

// ——— TypeScript ———
const [typescriptTrack, typescriptStages] = buildTrack({
  slug: "typescript",
  order: 8,
  title: { ar: "TypeScript", en: "TypeScript" },
  tagline: { ar: "JavaScript بأنواع — معيار الصناعة للواجهات والـ Node", en: "Typed JavaScript — the industry default for web & Node" },
  description: {
    ar: "TypeScript مطلوب في أغلب وظائف Frontend/Full-stack: الأنواع، الواجهات، Generics، والضبط مع Vite/Node.",
    en: "TypeScript is required in most frontend/full-stack jobs: types, interfaces, generics, and tooling with Vite/Node.",
  },
  color: "#3178C6",
  hours: 70,
  stages: [
    {
      slug: "01-types",
      order: 1,
      title: { ar: "نظام الأنواع", en: "Type system" },
      description: { ar: "من الأساسيات للاتحادات", en: "From basics to unions" },
      lessons: [
        L("01-why-ts", 1, 40, "لماذا TypeScript؟", "Why TypeScript?", "أخطاء أبكر وأدوات أقوى.", "Earlier errors and stronger tooling.",
          "TS أصبح افتراضياً في React وAngular وNode الحديث.", "TS is the default in modern React, Angular, and Node.",
          [["التحقق وقت البناء", "اكتشف الأخطاء قبل التشغيل.", "Compile-time checks", "Catch bugs before runtime."],
           ["DX", "إكمال تلقائي أوثق.", "DX", "More reliable autocomplete."]],
          "const title: string = 'AlefYa'", "typescript"),
        L("02-interfaces-unions", 2, 45, "Interfaces والاتحادات", "Interfaces & unions", "نمذجة البيانات بدقة.", "Model data precisely.",
          "الواجهات والاتحادات لغة تصميم API في الواجهة.", "Interfaces and unions are how frontends design APIs.",
          [["interface", "شكل الكائن.", "interface", "Object shape."],
           ["union", "قيم مسموحة محدودة.", "union", "Allowed value sets."]],
          "type Locale = 'ar' | 'en'\ninterface Track { slug: string; title: Record<Locale, string> }", "typescript"),
        L("03-generics", 3, 45, "Generics", "Generics", "دوال وأنواع عامة.", "Generic functions and types.",
          "Generics تمنع تكرار الأنواع في المكتبات.", "Generics stop type duplication in libraries.",
          [["<T>", "معامل نوع.", "<T>", "A type parameter."],
           ["utility types", "Partial وPick وغيرها.", "Utility types", "Partial, Pick, and more."]],
          "function wrap<T>(value: T) { return { value } }", "typescript"),
      ],
    },
    {
      slug: "02-tooling",
      order: 2,
      title: { ar: "الأدوات والممارسة", en: "Tooling & practice" },
      description: { ar: "tsconfig والمشاريع", en: "tsconfig and real projects" },
      lessons: [
        L("01-tsconfig", 1, 40, "tsconfig", "tsconfig", "strict mode.", "strict mode.",
          "إعداد صارم يعلّمك عادات صحيحة مبكراً.", "Strict settings teach good habits early.",
          [["strict", "فعّله من اليوم الأول.", "strict", "Enable from day one."],
           ["module", "ESM في المشاريع الحديثة.", "module", "ESM in modern projects."]],
          "{\n  \"compilerOptions\": { \"strict\": true, \"target\": \"ES2022\" }\n}", "json"),
        L("02-with-react-node", 2, 45, "TS مع React/Node", "TS with React/Node", "أنواع المكوّنات والـ API.", "Component and API types.",
          "نفس المهارات تُستخدم يومياً في الوظائف.", "The same skills show up daily on the job.",
          [["Props", "اكتب أنواع المكوّن.", "Props", "Type your components."],
           ["API types", "شارك الأنواع بين العميل والخادم.", "API types", "Share types across client and server."]],
          "type Props = { trackSlug: string }\nexport function Card({ trackSlug }: Props) { return null }", "tsx"),
        L("03-practice", 3, 50, "تمرين مسار", "Track exercise", "نمذج مسارات ألف ياء بأنواع.", "Model AlefYa tracks with types.",
          "ابنِ نماذج Track وCategory كاملة الأنواع.", "Build fully typed Track and Category models.",
          [["نماذج", "Track وLesson.", "Models", "Track and Lesson."],
           ["تحقق", "دع المترجم يرفض الحالات الخاطئة.", "Verify", "Let the compiler reject bad cases."]],
          "type Category = { slug: string; trackSlugs: string[] }", "typescript"),
      ],
    },
  ],
});

// ——— Node.js ———
const [nodejsTrack, nodejsStages] = buildTrack({
  slug: "nodejs",
  order: 9,
  title: { ar: "Node.js", en: "Node.js" },
  tagline: { ar: "JavaScript على الخادم — الأشهر لـ APIs الحديثة", en: "JavaScript on the server — the default for modern APIs" },
  description: {
    ar: "Node.js وExpress/Fastify لبناء REST APIs: الوحدات، HTTP، الوسطاء، المصادقة، والنشر.",
    en: "Node.js with Express/Fastify for REST APIs: modules, HTTP, middleware, auth, and deploy.",
  },
  color: "#339933",
  hours: 90,
  stages: [
    {
      slug: "01-core",
      order: 1,
      title: { ar: "أساسيات Node", en: "Node fundamentals" },
      description: { ar: "الحدث والوحدات", en: "Event loop and modules" },
      lessons: [
        L("01-why-node", 1, 40, "لماذا Node.js؟", "Why Node.js?", "لغة واحدة للواجهة والخادم.", "One language across client and server.",
          "Node من أكثر تقنيات الـ backend طلباً في الوظائف.", "Node is among the most requested backend skills in job posts.",
          [["Non-blocking", "يناسب I/O الكثيف مثل APIs.", "Non-blocking", "Fits I/O-heavy APIs."],
           ["نظام بيئي", "npm ضخم وناضج.", "Ecosystem", "A huge mature npm ecosystem."]],
          "console.log('AlefYa API')", "javascript"),
        L("02-modules-npm", 2, 45, "Modules وnpm", "Modules & npm", "ESM وpackage.json.", "ESM and package.json.",
          "إدارة الحزم جزء يومي من عمل الـ backend.", "Package management is daily backend work.",
          [["package.json", "اعتماديات وسكربتات.", "package.json", "Dependencies and scripts."],
           ["ESM", "import/export الحديثة.", "ESM", "Modern import/export."]],
          "{\n  \"type\": \"module\",\n  \"scripts\": { \"start\": \"node src/index.js\" }\n}", "json"),
        L("03-http-express", 3, 50, "HTTP وExpress", "HTTP & Express", "أول API.", "Your first API.",
          "Express ما زال المدخل الأشهر لـ Node APIs.", "Express remains the most common entry to Node APIs.",
          [["routes", "GET/POST.", "routes", "GET/POST."],
           ["middleware", "طبقات مشتركة.", "middleware", "Shared layers."]],
          "import express from 'express'\nconst app = express()\napp.get('/health', (_, res) => res.json({ ok: true }))\napp.listen(3000)", "javascript"),
      ],
    },
    {
      slug: "02-api",
      order: 2,
      title: { ar: "بناء API", en: "Building APIs" },
      description: { ar: "تحقق، مصادقة، هيكلة", en: "Validation, auth, structure" },
      lessons: [
        L("01-validation", 1, 45, "التحقق", "Validation", "Zod أو مشابه.", "Zod or similar.",
          "لا تثق بمدخلات العميل أبداً.", "Never trust client input.",
          [["schema", "عرّف الشكل المقبول.", "schema", "Define accepted shape."],
           ["errors", "ردود واضحة.", "errors", "Clear error responses."]],
          "const schema = z.object({ email: z.string().email() })", "javascript"),
        L("02-auth-jwt", 2, 50, "JWT Auth", "JWT auth", "تسجيل ودخول.", "Sign-up and login.",
          "المصادقة مهارة أساسية في أي Backend.", "Auth is a core backend skill.",
          [["hash", "كلمات المرور.", "hash", "Passwords."],
           ["JWT", "جلسات API.", "JWT", "API sessions."]],
          "const token = jwt.sign({ sub: userId }, process.env.SECRET)", "javascript"),
        L("03-project", 3, 55, "مشروع API", "API project", "مسارات تعلّم مصغّرة.", "Mini learning-path API.",
          "ابنِ endpoints للمسارات والتقدّم.", "Build endpoints for tracks and progress.",
          [["REST", "موارد واضحة.", "REST", "Clear resources."],
           ["تنظيم", "routes/services.", "Structure", "routes/services."]],
          "// GET /tracks  POST /progress", "javascript"),
      ],
    },
  ],
});

// ——— Python ———
const [pythonTrack, pythonStages] = buildTrack({
  slug: "python",
  order: 10,
  title: { ar: "Python", en: "Python" },
  tagline: { ar: "اللغة الأشهر للتعلم، الـ APIs، والبيانات", en: "The most popular language for learning, APIs, and data" },
  description: {
    ar: "Python مطلوبة بقوة: الصيغة، OOP، ثم FastAPI لبناء APIs حديثة بسرعة.",
    en: "Python is in huge demand: syntax, OOP, then FastAPI to ship modern APIs fast.",
  },
  color: "#3776AB",
  hours: 95,
  stages: [
    {
      slug: "01-language",
      order: 1,
      title: { ar: "لغة Python", en: "Python language" },
      description: { ar: "أساسيات قوية", en: "Strong foundations" },
      lessons: [
        L("01-why-python", 1, 40, "لماذا Python؟", "Why Python?", "تعلّم سريع وسوق واسع.", "Fast to learn, huge market.",
          "Python الأولى عالمياً في كثير من مؤشرات الشعبية.", "Python ranks #1 on many popularity indexes.",
          [["قراءة سهلة", "تركّز على المنطق.", "Readable", "Focus on logic."],
           ["مجالات", "ويب، بيانات، أتمتة، AI.", "Domains", "Web, data, automation, AI."]],
          "print('AlefYa')", "python"),
        L("02-syntax-types", 2, 45, "الصيغة والأنواع", "Syntax & types", "قوائم، قواميس، دوال.", "Lists, dicts, functions.",
          "هياكل البيانات المدمجة هي قوة Python اليومية.", "Built-in structures power daily Python work.",
          [["list/dict", "تخزين مرن.", "list/dict", "Flexible storage."],
           ["functions", "وحدات منطقية.", "functions", "Logical units."]],
          "def greet(name: str) -> str:\n    return f'Hello {name}'", "python"),
        L("03-oop", 3, 45, "OOP في Python", "OOP in Python", "classes.", "classes.",
          "النماذج والخدمات تُكتب كفئات.", "Models and services are written as classes.",
          [["class", "الحالة والسلوك.", "class", "State and behavior."],
           ["dataclass", "نماذج أنظف.", "dataclass", "Cleaner models."]],
          "from dataclasses import dataclass\n@dataclass\nclass Track:\n    slug: str", "python"),
      ],
    },
    {
      slug: "02-fastapi",
      order: 2,
      title: { ar: "FastAPI", en: "FastAPI" },
      description: { ar: "APIs حديثة وسريعة", en: "Modern fast APIs" },
      lessons: [
        L("01-fastapi-intro", 1, 45, "مدخل FastAPI", "FastAPI intro", "أول endpoint.", "First endpoint.",
          "FastAPI من أشهر أطر Python للـ APIs اليوم.", "FastAPI is one of today's most popular Python API frameworks.",
          [["Pydantic", "تحقق تلقائي.", "Pydantic", "Automatic validation."],
           ["docs", "Swagger مدمج.", "docs", "Built-in Swagger."]],
          "from fastapi import FastAPI\napp = FastAPI()\n@app.get('/health')\ndef health():\n    return {'ok': True}", "python"),
        L("02-models-routes", 2, 50, "النماذج والمسارات", "Models & routes", "CRUD بسيط.", "Simple CRUD.",
          "صمّم موارد واضحة للمسارات والدروس.", "Design clear resources for tracks and lessons.",
          [["BaseModel", "شكل الطلب/الرد.", "BaseModel", "Request/response shape."],
           ["path params", "معرّفات الموارد.", "path params", "Resource identifiers."]],
          "class TrackIn(BaseModel):\n    slug: str\n    title: str", "python"),
        L("03-project", 3, 55, "مشروع Python API", "Python API project", "خدمة تقدّم مصغّرة.", "Mini progress service.",
          "اربط النماذج والمسارات في خدمة صغيرة.", "Connect models and routes into a small service.",
          [["هيكلة", "routers وservices.", "Structure", "routers and services."],
           ["اختبار", "جرّب من /docs.", "Test", "Try via /docs."]],
          "# uvicorn main:app --reload", "bash"),
      ],
    },
  ],
});

// ——— PostgreSQL ———
const [postgresqlTrack, postgresqlStages] = buildTrack({
  slug: "postgresql",
  order: 11,
  title: { ar: "PostgreSQL", en: "PostgreSQL" },
  tagline: { ar: "قاعدة البيانات العلائقية الأقوى والأكثر طلباً", en: "The most in-demand relational database" },
  description: {
    ar: "SQL وPostgreSQL: الجداول، العلاقات، الفهارس، الاستعلامات، والمعاملات — أساس أي Backend جاد.",
    en: "SQL & PostgreSQL: tables, relations, indexes, queries, and transactions — the backbone of serious backends.",
  },
  color: "#336791",
  hours: 80,
  stages: [
    {
      slug: "01-sql",
      order: 1,
      title: { ar: "SQL الأساسي", en: "Core SQL" },
      description: { ar: "SELECT إلى JOIN", en: "SELECT to JOIN" },
      lessons: [
        L("01-why-postgres", 1, 40, "لماذا PostgreSQL؟", "Why PostgreSQL?", "موثوقية ومعيار صناعي.", "Reliability and industry standard.",
          "Postgres اختيار افتراضي لكثير من الشركات الناشئة والمؤسسات.", "Postgres is the default choice for many startups and enterprises.",
          [["SQL قياسي", "مهارات قابلة للنقل.", "Standard SQL", "Portable skills."],
           ["ميزات", "JSON، فهارس، امتدادات.", "Features", "JSON, indexes, extensions."]],
          "SELECT version();", "sql"),
        L("02-tables-crud", 2, 45, "الجداول وCRUD", "Tables & CRUD", "INSERT/UPDATE/DELETE.", "INSERT/UPDATE/DELETE.",
          "نمذجة الجداول أول مهارة عملية.", "Table modeling is the first practical skill.",
          [["CREATE TABLE", "عرّف الأعمدة.", "CREATE TABLE", "Define columns."],
           ["قيود", "PRIMARY/FOREIGN KEY.", "Constraints", "PRIMARY/FOREIGN KEY."]],
          "CREATE TABLE tracks (\n  id SERIAL PRIMARY KEY,\n  slug TEXT UNIQUE NOT NULL\n);", "sql"),
        L("03-joins", 3, 50, "JOIN", "JOIN", "ربط الجداول.", "Relate tables.",
          "العلاقات هي قوة القواعد العلائقية.", "Relations are the power of relational DBs.",
          [["INNER JOIN", "تقاطع الصفوف.", "INNER JOIN", "Matching rows."],
           ["LEFT JOIN", "أبقِ الطرف الأيسر.", "LEFT JOIN", "Keep the left side."]],
          "SELECT t.slug, p.lesson_slug\nFROM tracks t\nLEFT JOIN progress p ON p.track_id = t.id;", "sql"),
      ],
    },
    {
      slug: "02-performance",
      order: 2,
      title: { ar: "أداء ومعاملات", en: "Performance & transactions" },
      description: { ar: "فهارس وACID", en: "Indexes and ACID" },
      lessons: [
        L("01-indexes", 1, 45, "الفهارس", "Indexes", "تسريع القراءة.", "Speed up reads.",
          "بدون فهارس تتباطأ الاستعلامات مع نمو البيانات.", "Without indexes, queries slow as data grows.",
          [["B-Tree", "الافتراضي الأشهر.", "B-Tree", "The common default."],
           ["متى تفهرس", "أعمدة البحث المتكرر.", "When to index", "Frequently filtered columns."]],
          "CREATE INDEX idx_progress_user ON progress(user_id);", "sql"),
        L("02-transactions", 2, 45, "المعاملات", "Transactions", "الالتزام والتراجع.", "Commit and rollback.",
          "المعاملات تحمي تكامل البيانات.", "Transactions protect data integrity.",
          [["BEGIN/COMMIT", "وحدة عمل.", "BEGIN/COMMIT", "Unit of work."],
           ["ROLLBACK", "تراجع عند الخطأ.", "ROLLBACK", "Undo on failure."]],
          "BEGIN;\nUPDATE accounts SET balance = balance - 10 WHERE id = 1;\nCOMMIT;", "sql"),
        L("03-project", 3, 50, "مخطط ألف ياء", "AlefYa schema", "صمم جداول المسارات والتقدّم.", "Design tracks and progress tables.",
          "ارسم مخططاً كاملاً ثم اكتبه SQL.", "Sketch a full schema then write the SQL.",
          [["ERD", "كيانات وعلاقات.", "ERD", "Entities and relations."],
           ["تطبيق", "أنشئ الجداول.", "Apply", "Create the tables."]],
          "-- users, tracks, enrollments, progress", "sql"),
      ],
    },
  ],
});

// ——— MongoDB ———
const [mongodbTrack, mongodbStages] = buildTrack({
  slug: "mongodb",
  order: 12,
  title: { ar: "MongoDB", en: "MongoDB" },
  tagline: { ar: "قاعدة وثائق NoSQL الأشهر للتطبيقات الحديثة", en: "The most popular document NoSQL database for modern apps" },
  description: {
    ar: "MongoDB: الوثائق، الاستعلامات، الفهارس، والتجميع — شائعة جداً مع Node وPython.",
    en: "MongoDB: documents, queries, indexes, and aggregation — hugely common with Node and Python.",
  },
  color: "#47A248",
  hours: 75,
  stages: [
    {
      slug: "01-documents",
      order: 1,
      title: { ar: "نموذج الوثائق", en: "Document model" },
      description: { ar: "Collections وCRUD", en: "Collections and CRUD" },
      lessons: [
        L("01-why-mongo", 1, 40, "لماذا MongoDB؟", "Why MongoDB?", "مرونة المخطط وسرعة التطوير.", "Schema flexibility and speed of development.",
          "MongoDB من أكثر قواعد NoSQL استخداماً في المنتجات الحديثة.", "MongoDB is among the most used NoSQL databases in modern products.",
          [["Documents", "JSON-like.", "Documents", "JSON-like."],
           ["حالات الاستخدام", "كتالوج، محتوى، أحداث.", "Use cases", "Catalogs, content, events."]],
          "db.tracks.insertOne({ slug: 'react', title: 'React' })", "javascript"),
        L("02-crud-queries", 2, 45, "CRUD والاستعلام", "CRUD & queries", "find والتصفية.", "find and filters.",
          "أتقن أنماط الاستعلام اليومية.", "Master daily query patterns.",
          [["find", "قراءة الوثائق.", "find", "Read documents."],
           ["update", "تحديث جزئي.", "update", "Partial updates."]],
          "db.progress.find({ userId: 'u1', trackSlug: 'react' })", "javascript"),
        L("03-schema-design", 3, 45, "تصميم المخطط", "Schema design", "تضمين مقابل مرجع.", "Embed vs reference.",
          "قرار التضمين يغيّر أداء التطبيق.", "Embed vs reference decisions change app performance.",
          [["embed", "بيانات تُقرأ معاً.", "embed", "Data read together."],
           ["reference", "علاقات منفصلة.", "reference", "Separate relations."]],
          "// prefer embed for lesson lists inside a track doc when small", "javascript"),
      ],
    },
    {
      slug: "02-advanced",
      order: 2,
      title: { ar: "فهارس وتجميع", en: "Indexes & aggregation" },
      description: { ar: "أداء وتحليل", en: "Performance and analytics" },
      lessons: [
        L("01-indexes", 1, 40, "الفهارس في Mongo", "Mongo indexes", "تسريع find.", "Speed up find.",
          "الفهارس حاسمة مع نمو المجموعات.", "Indexes matter as collections grow.",
          [["createIndex", "أنشئ بوعي.", "createIndex", "Create intentionally."],
           ["compound", "فهارس مركّبة.", "compound", "Compound indexes."]],
          "db.progress.createIndex({ userId: 1, trackSlug: 1 })", "javascript"),
        L("02-aggregation", 2, 50, "Aggregation", "Aggregation", "pipelines.", "pipelines.",
          "التجميع قوي للتقارير والإحصاءات.", "Aggregation is powerful for reports and stats.",
          [["$match/$group", "لبّ الـ pipeline.", "$match/$group", "Pipeline core."],
           ["أمثلة", "عدّ الدروس المكتملة.", "Examples", "Count completed lessons."]],
          "db.progress.aggregate([\n  { $match: { userId: 'u1' } },\n  { $group: { _id: '$trackSlug', n: { $sum: 1 } } }\n])", "javascript"),
        L("03-project", 3, 50, "مشروع وثائق", "Documents project", "صمّم مجموعات ألف ياء.", "Design AlefYa collections.",
          "اكتب مخطط وثائق للمسارات والتسجيلات.", "Write a document schema for tracks and enrollments.",
          [["مجموعات", "tracks/progress.", "Collections", "tracks/progress."],
           ["فهارس", "أضف ما يلزم.", "Indexes", "Add what you need."]],
          "// tracks, enrollments, progress collections", "javascript"),
      ],
    },
  ],
});

// ——— Docker ———
const [dockerTrack, dockerStages] = buildTrack({
  slug: "docker",
  order: 13,
  title: { ar: "Docker", en: "Docker" },
  tagline: { ar: "حاويات أصبحت مهارة إلزامية لأي مطوّر جاد", en: "Containers — a must-have skill for serious developers" },
  description: {
    ar: "Docker: الصور، الحاويات، Dockerfile، وCompose لتشغيل التطبيقات بنفس الطريقة في كل بيئة.",
    en: "Docker: images, containers, Dockerfiles, and Compose to run apps the same way everywhere.",
  },
  color: "#2496ED",
  hours: 65,
  stages: [
    {
      slug: "01-containers",
      order: 1,
      title: { ar: "الحاويات", en: "Containers" },
      description: { ar: "مفاهيم التشغيل", en: "Runtime concepts" },
      lessons: [
        L("01-why-docker", 1, 40, "لماذا Docker؟", "Why Docker?", "نفس البيئة للجميع.", "Same environment for everyone.",
          "Docker مهارة تطلبها تقريباً كل فرق الهندسة اليوم.", "Docker is requested by almost every engineering team today.",
          [["عزل", "تبعيات داخل الحاوية.", "Isolation", "Dependencies inside the container."],
           ["قابلية النقل", "من اللابتوب للسيرفر.", "Portability", "Laptop to server."]],
          "docker run hello-world", "bash"),
        L("02-images-containers", 2, 45, "Images وContainers", "Images & containers", "تشغيل وإيقاف.", "Run and stop.",
          "افهم الفرق بين الصورة والحاوية.", "Know image vs container.",
          [["image", "قالب للقراءة.", "image", "Read-only template."],
           ["container", "نسخة شغّالة.", "container", "A running instance."]],
          "docker ps -a\ndocker stop <id>", "bash"),
        L("03-dockerfile", 3, 50, "Dockerfile", "Dockerfile", "ابنِ صورتك.", "Build your image.",
          "Dockerfile هو وصفة بناء التطبيق.", "A Dockerfile is your app's build recipe.",
          [["FROM/COPY/RUN", "طبقات الصورة.", "FROM/COPY/RUN", "Image layers."],
           [".dockerignore", "استبعد الزائد.", ".dockerignore", "Exclude noise."]],
          "FROM node:22-alpine\nWORKDIR /app\nCOPY package*.json .\nRUN npm ci\nCOPY . .\nCMD [\"npm\",\"start\"]", "dockerfile"),
      ],
    },
    {
      slug: "02-compose",
      order: 2,
      title: { ar: "Compose", en: "Compose" },
      description: { ar: "خدمات متعددة", en: "Multi-service stacks" },
      lessons: [
        L("01-compose-basics", 1, 45, "Docker Compose", "Docker Compose", "app + db.", "app + db.",
          "Compose يشغّل منظومة كاملة بأمر واحد.", "Compose runs a whole stack with one command.",
          [["services", "عرّف الخدمات.", "services", "Declare services."],
           ["volumes", "ثبات البيانات.", "volumes", "Persist data."]],
          "services:\n  api:\n    build: .\n    ports: ['3000:3000']\n  db:\n    image: postgres:16", "yaml"),
        L("02-dev-workflow", 2, 45, "سير عمل التطوير", "Dev workflow", "إعادة البناء والسجلات.", "Rebuilds and logs.",
          "استخدم Compose يومياً في التطوير المحلي.", "Use Compose daily for local development.",
          [["logs", "تشخيص سريع.", "logs", "Fast diagnosis."],
           ["rebuild", "بعد تغيير Dockerfile.", "rebuild", "After Dockerfile changes."]],
          "docker compose up --build", "bash"),
        L("03-project", 3, 50, "حاوية ألف ياء", "Containerize AlefYa", "API + Postgres.", "API + Postgres.",
          "اكتب Compose لتطبيق تعلّم بسيط.", "Write Compose for a simple learning app.",
          [["خدمات", "web/api/db.", "Services", "web/api/db."],
           ["اختبار", "افتح المنفذ محلياً.", "Test", "Open the port locally."]],
          "docker compose up", "bash"),
      ],
    },
  ],
});

// ——— Kubernetes ———
const [kubernetesTrack, kubernetesStages] = buildTrack({
  slug: "kubernetes",
  order: 14,
  title: { ar: "Kubernetes", en: "Kubernetes" },
  tagline: { ar: "منصة تشغيل الحاويات القياسية في الشركات", en: "The industry-standard container orchestration platform" },
  description: {
    ar: "Kubernetes (K8s): Pods، Deployments، Services، وتهيئة أساسية لنشر تطبيقات حقيقية.",
    en: "Kubernetes (K8s): Pods, Deployments, Services, and core config to ship real workloads.",
  },
  color: "#326CE5",
  hours: 85,
  stages: [
    {
      slug: "01-core",
      order: 1,
      title: { ar: "مفاهيم K8s", en: "K8s concepts" },
      description: { ar: "العنقود والكائنات", en: "Cluster and objects" },
      lessons: [
        L("01-why-k8s", 1, 40, "لماذا Kubernetes؟", "Why Kubernetes?", "تشغيل واسع وموثوق.", "Scale with reliability.",
          "K8s المهارة الأكثر طلباً في DevOps/Platform.", "K8s is one of the most requested DevOps/platform skills.",
          [["Orchestration", "جدول الحاويات.", "Orchestration", "Schedule containers."],
           ["Self-heal", "إعادة التشغيل التلقائي.", "Self-heal", "Automatic restarts."]],
          "kubectl version --client", "bash"),
        L("02-pods-deployments", 2, 50, "Pods وDeployments", "Pods & Deployments", "تشغيل نسخة من تطبيقك.", "Run a replica of your app.",
          "Deployment يدير التحديثات والنسخ.", "Deployments manage rollouts and replicas.",
          [["Pod", "أصغر وحدة تشغيل.", "Pod", "Smallest runnable unit."],
           ["replicas", "التوفر.", "replicas", "Availability."]],
          "kubectl create deployment web --image=nginx", "bash"),
        L("03-services", 3, 45, "Services", "Services", "تعريض الشبكة.", "Expose networking.",
          "Service يعطي عنواناً ثابتاً للـ Pods.", "A Service gives Pods a stable address.",
          [["ClusterIP", "داخلي.", "ClusterIP", "Internal."],
           ["NodePort/LB", "وصول خارجي.", "NodePort/LB", "External access."]],
          "kubectl expose deployment web --port=80 --type=ClusterIP", "bash"),
      ],
    },
    {
      slug: "02-ship",
      order: 2,
      title: { ar: "تهيئة ونشر", en: "Config & shipping" },
      description: { ar: "YAML عملي", en: "Practical YAML" },
      lessons: [
        L("01-yaml-manifests", 1, 45, "ملفات YAML", "YAML manifests", "اكتب Deployment كاملاً.", "Write a full Deployment.",
          "الملفات التصريحية هي لغة Kubernetes.", "Declarative files are Kubernetes' language.",
          [["apiVersion/kind", "هوية المورد.", "apiVersion/kind", "Resource identity."],
           ["apply", "طبّق الحالة المطلوبة.", "apply", "Apply desired state."]],
          "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: api\nspec:\n  replicas: 2\n  selector:\n    matchLabels: { app: api }\n  template:\n    metadata:\n      labels: { app: api }\n    spec:\n      containers:\n        - name: api\n          image: ghcr.io/example/api:1", "yaml"),
        L("02-config-secrets", 2, 45, "ConfigMaps وSecrets", "ConfigMaps & Secrets", "إعداد بدون إعادة بناء الصورة.", "Config without rebuilding images.",
          "افصل الإعداد عن الصورة.", "Separate config from the image.",
          [["ConfigMap", "إعداد غير حسّاس.", "ConfigMap", "Non-sensitive config."],
           ["Secret", "أسرار مشفّرة عند التخزين.", "Secret", "Sensitive values at rest."]],
          "kubectl create configmap app-config --from-literal=NODE_ENV=production", "bash"),
        L("03-project", 3, 55, "نشر خدمة تعلّم", "Deploy a learning API", "Deployment + Service.", "Deployment + Service.",
          "انشر API بسيطاً وتعرّضه داخل العنقود.", "Deploy a small API and expose it in-cluster.",
          [["مخطط", "ملفات YAML.", "Plan", "YAML files."],
           ["تحقق", "kubectl get pods.", "Verify", "kubectl get pods."]],
          "kubectl apply -f k8s/", "bash"),
      ],
    },
  ],
});

// ——— JavaScript fundamentals ———
const [javascriptTrack, javascriptStages] = buildTrack({
  slug: "javascript",
  order: 15,
  title: { ar: "JavaScript", en: "JavaScript" },
  tagline: { ar: "لغة الويب — الأساس قبل أي إطار", en: "The language of the web — master it before any framework" },
  description: {
    ar: "JavaScript الحديث: الصيغة، الدوال، المصفوفات، DOM، والـ asynchronous — مطلوب قبل React/Vue/Node.",
    en: "Modern JavaScript: syntax, functions, arrays, DOM, and async — required before React/Vue/Node.",
  },
  color: "#F7DF1E",
  hours: 80,
  stages: [
    {
      slug: "01-language",
      order: 1,
      title: { ar: "أساسيات اللغة", en: "Language basics" },
      description: { ar: "من المتغيرات للدوال", en: "From variables to functions" },
      lessons: [
        L("01-why-js", 1, 35, "لماذا JavaScript؟", "Why JavaScript?", "لغة المتصفح وNode.", "Browser and Node language.",
          "JS أساس تقريباً كل مسار Frontend وكثير من الـ Backend.", "JS underpins almost every frontend path and much backend work.",
          [["في كل مكان", "متصفح + خادم.", "Everywhere", "Browser + server."],
           ["قبل الأطر", "لا تقفز لـ React قبل JS.", "Before frameworks", "Don't jump to React before JS."]],
          "console.log('AlefYa')", "javascript"),
        L("02-syntax-control", 2, 45, "الصيغة والتحكم", "Syntax & control flow", "if/loops.", "if/loops.",
          "التحكم بالتدفق أساس أي خوارزمية بسيطة.", "Control flow is the base of simple algorithms.",
          [["let/const", "تجنّب var.", "let/const", "Avoid var."],
           ["loops", "for وfor...of.", "loops", "for and for...of."]],
          "const n = 3\nfor (let i = 0; i < n; i++) console.log(i)", "javascript"),
        L("03-functions-arrays", 3, 50, "الدوال والمصفوفات", "Functions & arrays", "map/filter.", "map/filter.",
          "معالجة المصفوفات مهارة يومية.", "Array processing is a daily skill.",
          [["map/filter", "تحوّل بدون تشويش.", "map/filter", "Transform cleanly."],
           ["arrow functions", "اختصار شائع.", "arrow functions", "Common shorthand."]],
          "const slugs = tracks.map(t => t.slug)", "javascript"),
      ],
    },
    {
      slug: "02-browser-async",
      order: 2,
      title: { ar: "المتصفح وAsync", en: "Browser & async" },
      description: { ar: "DOM وPromises", en: "DOM and Promises" },
      lessons: [
        L("01-dom", 1, 45, "DOM", "DOM", "اختيار وتحديث العناصر.", "Select and update elements.",
          "فهم DOM يوضح ما تفعله الأطر خلف الكواليس.", "DOM literacy clarifies what frameworks do under the hood.",
          [["querySelector", "اختر عنصر.", "querySelector", "Select an element."],
           ["events", "استمع للنقر.", "events", "Listen for clicks."]],
          "document.querySelector('#app').textContent = 'AlefYa'", "javascript"),
        L("02-async", 2, 50, "Promises وasync/await", "Promises & async/await", "جلب بيانات.", "Fetching data.",
          "البرمجة غير المتزامنة أساس الويب الحديث.", "Async programming is the base of modern web apps.",
          [["Promise", "قيمة مستقبلية.", "Promise", "A future value."],
           ["fetch", "HTTP من المتصفح.", "fetch", "HTTP from the browser."]],
          "const res = await fetch('/api/tracks')\nconst data = await res.json()", "javascript"),
        L("03-project", 3, 50, "مشروع JS صغير", "Small JS project", "قائمة مسارات تفاعلية.", "Interactive tracks list.",
          "ابنِ صفحة تعرض تصنيفات بدون إطار.", "Build a categories page without a framework.",
          [["HTML+JS", "اربط الأحداث.", "HTML+JS", "Wire events."],
           ["بيانات", "مصفوفة محلية.", "Data", "Local array."]],
          "// render categories into #list", "javascript"),
      ],
    },
  ],
});

// ——— Git ———
const [gitTrack, gitStages] = buildTrack({
  slug: "git",
  order: 16,
  title: { ar: "Git & GitHub", en: "Git & GitHub" },
  tagline: { ar: "أداة لا غنى عنها لكل مطوّر في أي فريق", en: "The non-negotiable tool for every developer and team" },
  description: {
    ar: "Git وGitHub: الالتزامات، الفروع، الدمج، وPull Requests — مهارة مطلوبة في كل وظيفة تقريباً.",
    en: "Git & GitHub: commits, branches, merges, and pull requests — required in almost every job.",
  },
  color: "#F05032",
  hours: 45,
  stages: [
    {
      slug: "01-basics",
      order: 1,
      title: { ar: "أساسيات Git", en: "Git basics" },
      description: { ar: "مستودع محلي", en: "Local repo" },
      lessons: [
        L("01-why-git", 1, 35, "لماذا Git؟", "Why Git?", "تاريخ التغييرات والعمل الجماعي.", "Change history and teamwork.",
          "بدون Git يصعب التوظيف أو التعاون الجاد.", "Without Git, serious collaboration and hiring are hard.",
          [["version control", "تتبع كل تغيير.", "version control", "Track every change."],
           ["GitHub", "استضافة وتعاون.", "GitHub", "Hosting and collaboration."]],
          "git --version", "bash"),
        L("02-commit", 2, 40, "Commit", "Commit", "add وcommit.", "add and commit.",
          "الالتزامات الجيدة توثّق القصد.", "Good commits document intent.",
          [["staging", "اختر ما يُحفظ.", "staging", "Choose what to save."],
           ["رسالة", "اكتب لماذا لا ماذا فقط.", "message", "Write why, not only what."]],
          "git add .\ngit commit -m \"add categories homepage\"", "bash"),
        L("03-branch-merge", 3, 45, "الفروع والدمج", "Branches & merge", "عمل متوازٍ.", "Parallel work.",
          "الفروع أساس العمل على الميزات.", "Branches are how features get built.",
          [["branch", "خط تطوير مستقل.", "branch", "Independent line of work."],
           ["merge", "دمج التغييرات.", "merge", "Integrate changes."]],
          "git switch -c feature/flutter-track\ngit switch main\ngit merge feature/flutter-track", "bash"),
      ],
    },
    {
      slug: "02-github",
      order: 2,
      title: { ar: "GitHub", en: "GitHub" },
      description: { ar: "Remote وPRs", en: "Remotes and PRs" },
      lessons: [
        L("01-remote", 1, 40, "Remote", "Remote", "push/pull.", "push/pull.",
          "المستودع البعيد يحفظ عملك ويشارك الفريق.", "A remote saves your work and shares with the team.",
          [["origin", "العنوان البعيد.", "origin", "The remote name."],
           ["push", "ارفع الفروع.", "push", "Publish branches."]],
          "git remote add origin git@github.com:you/alefya.git\ngit push -u origin main", "bash"),
        L("02-pull-requests", 2, 45, "Pull Requests", "Pull Requests", "مراجعة الكود.", "Code review.",
          "الـ PR طريقة الفرق المحترفة لدمج العمل.", "PRs are how professional teams merge work.",
          [["PR", "اقترح دمج فرع.", "PR", "Propose merging a branch."],
           ["review", "نقاش وتحسين.", "review", "Discuss and improve."]],
          "# open a PR from feature branch → main", "bash"),
        L("03-workflow", 3, 40, "سير عمل يومي", "Daily workflow", "عادات الفريق.", "Team habits.",
          "اتبع مساراً بسيطاً: فرع → commit → push → PR.", "Follow a simple path: branch → commit → push → PR.",
          [["habit", "كُمّل صغير ومتكرر.", "habit", "Small frequent commits."],
           ["conflicts", "حلّ التعارض بهدوء.", "conflicts", "Resolve conflicts calmly."]],
          "git status\ngit pull --rebase", "bash"),
      ],
    },
  ],
});

export const popularTrackBundles = [
  [flutterTrack, flutterStages],
  [vueTrack, vueStages],
  [typescriptTrack, typescriptStages],
  [nodejsTrack, nodejsStages],
  [pythonTrack, pythonStages],
  [postgresqlTrack, postgresqlStages],
  [mongodbTrack, mongodbStages],
  [dockerTrack, dockerStages],
  [kubernetesTrack, kubernetesStages],
  [javascriptTrack, javascriptStages],
  [gitTrack, gitStages],
];
